import { Difficult } from './indicate';

export const DIFFICULTS_17P7: Difficult[] = [
  { id: 1, difficult:17, rank:'', grade:'', name: 'Ganymede kamome mix', score:0, cols: 1, rows: 1}, 
  { id: 2, difficult:17, rank:'', grade:'', name: 'Joyeuse', score:0, cols: 1, rows: 1}, 
  { id: 3, difficult:17, rank:'', grade:'', name: 'Shanghai Wu Long ～上海舞龍～', score:0, cols: 1, rows: 1}, 
  { id: 4, difficult:17, rank:'', grade:'', name: '超☆超☆光☆速☆出☆前☆最☆速!!! スピード★スター★かなで', score:0, cols: 1, rows: 1}, 
  { id: 5, difficult:17, rank:'', grade:'', name: 'Verse IV', score:0, cols: 1, rows: 1}, 
  { id: 6, difficult:17, rank:'', grade:'', name: 'Last Concerto', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:17, rank:'', grade:'', name: 'Pet Peeve', score:0 , cols: 1, rows: 1},
  { id: 8, difficult:17, rank:'', grade:'', name: 'Opium and Purple haze', score:0, cols: 1, rows: 1}, 
  { id: 9, difficult:17, rank:'', grade:'', name: 'ENDYMION', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:17, rank:'', grade:'', name: 'Chant du Cygne', score:0 , cols: 1, rows: 1},
  { id: 11, difficult:17, rank:'', grade:'', name: 'Dyscontrolled Galaxy', score:0, cols: 1, rows: 1}, 
  { id: 12, difficult:17, rank:'', grade:'', name: 'Line 4 Ruin -kohumix-', score:0, cols: 1, rows: 1}, 
  { id: 13, difficult:17, rank:'', grade:'', name: 'Harpuia', score:0, cols: 1, rows: 1}, 
  { id: 14, difficult:17, rank:'', grade:'', name: 'U.N.オーエンは彼女なのか？haru_naba Remix', score:0, cols: 1, rows: 1}, 
  { id: 15, difficult:17, rank:'', grade:'', name: 'Pure Evil (Kobaryo FTN-Remix)', score:0, cols: 1, rows: 1}, 
  { id: 16, difficult:17, rank:'', grade:'', name: 'BabeL ～Next Story～', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:17, rank:'', grade:'', name: 'Candy Colored Hearts', score:0 , cols: 1, rows: 1},
  { id: 18, difficult:17, rank:'', grade:'', name: '超越してしまった彼女と其を生み落した理由', score:0, cols: 1, rows: 1}, 
  { id: 19, difficult:17, rank:'', grade:'', name: '香港功夫大旋風', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:17, rank:'', grade:'', name: 'Me:Tear', score:0 , cols: 1, rows: 1}
]


export const DIFFICULTS_17P6: Difficult[] = [
  { id: 1, difficult:17, rank:'', grade:'', name: 'freaky freak', score:0, cols: 1, rows: 1}, 
  { id: 2, difficult:17, rank:'', grade:'', name: 'rhythmology study', score:0, cols: 1, rows: 1}, 
  { id: 3, difficult:17, rank:'', grade:'', name: 'The world of sound', score:0, cols: 1, rows: 1}, 
  { id: 4, difficult:17, rank:'', grade:'', name: 'Witch in Sweetsland', score:0, cols: 1, rows: 1}, 
  { id: 5, difficult:17, rank:'', grade:'', name: 'Got more raves？', score:0, cols: 1, rows: 1}, 
  { id: 6, difficult:17, rank:'', grade:'', name: 'ムーニャポヨポヨスッポコニャーゴ', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:17, rank:'', grade:'', name: 'ほおずき程度には赤い頭髪', score:0 , cols: 1, rows: 1},
  { id: 8, difficult:17, rank:'', grade:'', name: 'LubedeR', score:0, cols: 1, rows: 1}, 
  { id: 9, difficult:17, rank:'', grade:'', name: 'The End of War', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:17, rank:'', grade:'', name: 'Nofram', score:0 , cols: 1, rows: 1},
  { id: 11, difficult:17, rank:'', grade:'', name: 'Quietus Ray', score:0, cols: 1, rows: 1}, 
  { id: 12, difficult:17, rank:'', grade:'', name: 'Garakuta Doll Play', score:0, cols: 1, rows: 1}, 
  { id: 13, difficult:17, rank:'', grade:'', name: 'Vampire\'s Territory', score:0, cols: 1, rows: 1}, 
  { id: 14, difficult:17, rank:'', grade:'', name: 'Enigma', score:0, cols: 1, rows: 1}, 
  { id: 15, difficult:17, rank:'', grade:'', name: 'Halcyon', score:0, cols: 1, rows: 1}, 
  { id: 16, difficult:17, rank:'', grade:'', name: 'Sakura Mirage', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:17, rank:'', grade:'', name: 'Sakura Mirage -Drum\'n World-', score:0 , cols: 1, rows: 1},
  { id: 18, difficult:17, rank:'', grade:'', name: '量子の海のリントヴルム', score:0, cols: 1, rows: 1}, 
  { id: 19, difficult:17, rank:'', grade:'', name: 'MAXIVCORD', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:17, rank:'', grade:'', name: 'AA BlackY mix', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:17, rank:'', grade:'', name: 'Pure Evil-Aya2g Drm\'n Tech Rmx-', score:0, cols: 1, rows: 1}, 
  { id: 22, difficult:17, rank:'', grade:'', name: 'StrayedCatz', score:0, cols: 1, rows: 1}, 
  { id: 23, difficult:17, rank:'', grade:'', name: 'A Lasting Promise', score:0, cols: 1, rows: 1}, 
  { id: 24, difficult:17, rank:'', grade:'', name: 'continew', score:0, cols: 1, rows: 1}, 
  { id: 25, difficult:17, rank:'', grade:'', name: 'ウエンレラの氷華', score:0, cols: 1, rows: 1}, 
  { id: 26, difficult:17, rank:'', grade:'', name: 'Ghost Family Living In Graveyard', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:17, rank:'', grade:'', name: 'Fiat Lux', score:0 , cols: 1, rows: 1},
  { id: 28, difficult:17, rank:'', grade:'', name: 'le coeur patissiere', score:0, cols: 1, rows: 1}, 
  { id: 29, difficult:17, rank:'', grade:'', name: 'Non RolicK!!大冒険', score:0 , cols: 1, rows: 1},
  { id: 30, difficult:17, rank:'', grade:'', name: '無双', score:0 , cols: 1, rows: 1}
]


export const DIFFICULTS_17P5: Difficult[] = [
  { id: 1, difficult:17, rank:'', grade:'', name: 'コメット⇒スケイター', score:0, cols: 1, rows: 1}, 
  { id: 2, difficult:17, rank:'', grade:'', name: '暴走', score:0, cols: 1, rows: 1}, 
  { id: 3, difficult:17, rank:'', grade:'', name: '飄える翼追い掛けて', score:0, cols: 1, rows: 1}, 
  { id: 4, difficult:17, rank:'', grade:'', name: 'CODE -CRiMSON-', score:0, cols: 1, rows: 1}, 
  { id: 5, difficult:17, rank:'', grade:'', name: 'iLLness LiLin', score:0, cols: 1, rows: 1}, 
  { id: 6, difficult:17, rank:'', grade:'', name: 'パ→ピ→プ→Yeah!', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:17, rank:'', grade:'', name: 'All Clear!!', score:0 , cols: 1, rows: 1},
  { id: 8, difficult:17, rank:'', grade:'', name: 'Aliquam', score:0, cols: 1, rows: 1}, 
  { id: 9, difficult:17, rank:'', grade:'', name: 'Sharkbait', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:17, rank:'', grade:'', name: 'Bioslaves', score:0 , cols: 1, rows: 1},
  { id: 11, difficult:17, rank:'', grade:'', name: 'JUGGLE', score:0, cols: 1, rows: 1}, 
  { id: 12, difficult:17, rank:'', grade:'', name: '打打打打打打打打打打', score:0, cols: 1, rows: 1}, 
  { id: 13, difficult:17, rank:'', grade:'', name: 'Decretum', score:0, cols: 1, rows: 1}, 
  { id: 14, difficult:17, rank:'', grade:'', name: 'gigadelic(m3rkAb4# R3m!x)', score:0, cols: 1, rows: 1}, 
  { id: 15, difficult:17, rank:'', grade:'', name: 'THUNDERCRACK', score:0, cols: 1, rows: 1}, 
  { id: 16, difficult:17, rank:'', grade:'', name: 'CRITICAL LINE', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:17, rank:'', grade:'', name: 'ホーンテッド★メイドランチ', score:0 , cols: 1, rows: 1},
  { id: 18, difficult:17, rank:'', grade:'', name: '物凄い狂っとるフランちゃんが物凄いうた', score:0, cols: 1, rows: 1}, 
  { id: 19, difficult:17, rank:'', grade:'', name: 'HE4VEN ～天国へようこそ～', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:17, rank:'', grade:'', name: '闇夜に舞うは紅の華', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:17, rank:'', grade:'', name: '音楽 -壊音楽 mix-', score:0, cols: 1, rows: 1}, 
  { id: 22, difficult:17, rank:'', grade:'', name: '音楽 -resolve-', score:0, cols: 1, rows: 1}, 
  { id: 23, difficult:17, rank:'', grade:'', name: 'Circulator', score:0, cols: 1, rows: 1}, 
  { id: 24, difficult:17, rank:'', grade:'', name: 'gigadelic -stance xxxx-', score:0, cols: 1, rows: 1}, 
  { id: 25, difficult:17, rank:'', grade:'', name: 'ΕΛΠΙΣ', score:0, cols: 1, rows: 1}, 
  { id: 26, difficult:17, rank:'', grade:'', name: '金縛りの逢を', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:17, rank:'', grade:'', name: 'Aragami', score:0 , cols: 1, rows: 1},
  { id: 28, difficult:17, rank:'', grade:'', name: 'GERBERA-For Finalists-', score:0, cols: 1, rows: 1}, 
  { id: 29, difficult:17, rank:'', grade:'', name: '2 MINUTES FIGHTERS', score:0 , cols: 1, rows: 1},
  { id: 30, difficult:17, rank:'', grade:'', name: 'Gott', score:0 , cols: 1, rows: 1},
  { id: 31, difficult:17, rank:'', grade:'', name: 'FLYING OUT TO THE SKY', score:0, cols: 1, rows: 1}, 
  { id: 32, difficult:17, rank:'', grade:'', name: 'HAELEQUIN', score:0, cols: 1, rows: 1}, 
  { id: 33, difficult:17, rank:'', grade:'', name: 'TOXIC VIBRATION', score:0, cols: 1, rows: 1}, 
  { id: 34, difficult:17, rank:'', grade:'', name: 'キャプテン・マリンのケツアンカー', score:0, cols: 1, rows: 1}, 
  { id: 35, difficult:17, rank:'', grade:'', name: 'M-O-R-F-I-N-E', score:0, cols: 1, rows: 1}
]


export const DIFFICULTS_17P4: Difficult[] = [
  { id: 1, difficult:17, rank:'', grade:'', name: 'Fly far bounce', score:0, cols: 1, rows: 1}, 
  { id: 2, difficult:17, rank:'', grade:'', name: 'プラネタジャーニー', score:0, cols: 1, rows: 1}, 
  { id: 3, difficult:17, rank:'', grade:'', name: '獅子奮迅', score:0, cols: 1, rows: 1}, 
  { id: 4, difficult:17, rank:'', grade:'', name: '羅生門', score:0, cols: 1, rows: 1}, 
  { id: 5, difficult:17, rank:'', grade:'', name: '黒髪乱れし修羅となりて～凛 edition～', score:0, cols: 1, rows: 1}, 
  { id: 6, difficult:17, rank:'', grade:'', name: 'Zelophilia', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:17, rank:'', grade:'', name: 'HYENA', score:0 , cols: 1, rows: 1},
  { id: 8, difficult:17, rank:'', grade:'', name: '０=Xerostrumental=', score:0, cols: 1, rows: 1}, 
  { id: 9, difficult:17, rank:'', grade:'', name: 'Enigma II', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:17, rank:'', grade:'', name: 'EBONY & IVORY', score:0 , cols: 1, rows: 1},
  { id: 11, difficult:17, rank:'', grade:'', name: 'Deadly Dolly Dance', score:0, cols: 1, rows: 1}, 
  { id: 12, difficult:17, rank:'', grade:'', name: 'TENKAICHI ULTIMATE BOSSRUSH MEDLEY', score:0, cols: 1, rows: 1}, 
  { id: 13, difficult:17, rank:'', grade:'', name: 'good high school', score:0, cols: 1, rows: 1}, 
  { id: 14, difficult:17, rank:'', grade:'', name: 'Historia of Velnoti', score:0, cols: 1, rows: 1}, 
  { id: 15, difficult:17, rank:'', grade:'', name: 'Cy-Bird', score:0, cols: 1, rows: 1}, 
  { id: 16, difficult:17, rank:'', grade:'', name: 'Voynich:Manuscript', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:17, rank:'', grade:'', name: 'Help me, ERINNNNNN!! -Cranky remix-', score:0 , cols: 1, rows: 1},
  { id: 18, difficult:17, rank:'', grade:'', name: 'conflict', score:0, cols: 1, rows: 1}, 
  { id: 19, difficult:17, rank:'', grade:'', name: 'False Cross', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:17, rank:'', grade:'', name: 'Destroy', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:17, rank:'', grade:'', name: 'Absolute Domination', score:0, cols: 1, rows: 1}, 
  { id: 22, difficult:17, rank:'', grade:'', name: '雪月花 -さわわRemix-', score:0, cols: 1, rows: 1}, 
  { id: 23, difficult:17, rank:'', grade:'', name: 'XROSS INFECTION', score:0, cols: 1, rows: 1}, 
  { id: 24, difficult:17, rank:'', grade:'', name: 'Get back here', score:0, cols: 1, rows: 1}, 
  { id: 25, difficult:17, rank:'', grade:'', name: 'そして紫の幻想曲は全てを受け入れる', score:0, cols: 1, rows: 1}, 
  { id: 26, difficult:17, rank:'', grade:'', name: '少年は空を辿る Prog Piano Remix', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:17, rank:'', grade:'', name: 'Dynasty', score:0 , cols: 1, rows: 1},
  { id: 28, difficult:17, rank:'', grade:'', name: 'Pieces of a Dream', score:0, cols: 1, rows: 1}, 
  { id: 29, difficult:17, rank:'', grade:'', name: 'NEON WORLD', score:0 , cols: 1, rows: 1},
  { id: 30, difficult:17, rank:'', grade:'', name: 'snow storm -euphoria-', score:0 , cols: 1, rows: 1},
  { id: 31, difficult:17, rank:'', grade:'', name: 'ナイト・オブ・ナイツ', score:0, cols: 1, rows: 1}, 
  { id: 32, difficult:17, rank:'', grade:'', name: '人形裁判 -THIRD IMPACT-', score:0, cols: 1, rows: 1}, 
  { id: 33, difficult:17, rank:'', grade:'', name: 'vivid landscape', score:0, cols: 1, rows: 1}, 
  { id: 34, difficult:17, rank:'', grade:'', name: 'ネメシス SDVX Edit', score:0, cols: 1, rows: 1}, 
  { id: 35, difficult:17, rank:'', grade:'', name: 'Dualive', score:0, cols: 1, rows: 1}, 
  { id: 36, difficult:17, rank:'', grade:'', name: 'Poison AND÷OR Affection', score:0 , cols: 1, rows: 1},
  { id: 37, difficult:17, rank:'', grade:'', name: 'Our Faith (Faithful MTL Remix)', score:0 , cols: 1, rows: 1},
  { id: 38, difficult:17, rank:'', grade:'', name: '神にした彼女が示す世界線', score:0, cols: 1, rows: 1}, 
  { id: 39, difficult:17, rank:'', grade:'', name: 'ディスコルディア', score:0 , cols: 1, rows: 1},
  { id: 40, difficult:17, rank:'', grade:'', name: 'Chewingood', score:0 , cols: 1, rows: 1}
]


export const DIFFICULTS_17P3: Difficult[] = [
  { id: 1, difficult:17, rank:'', grade:'', name: 'JOMANDA', score:0, cols: 1, rows: 1}, 
  { id: 2, difficult:17, rank:'', grade:'', name: '雲の彼方', score:0, cols: 1, rows: 1}, 
  { id: 3, difficult:17, rank:'', grade:'', name: '卑弥呼', score:0, cols: 1, rows: 1}, 
  { id: 4, difficult:17, rank:'', grade:'', name: 'Libera me', score:0, cols: 1, rows: 1}, 
  { id: 5, difficult:17, rank:'', grade:'', name: 'Musha Vibration', score:0, cols: 1, rows: 1}, 
  { id: 6, difficult:17, rank:'', grade:'', name: 'TWO-TORIAL', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:17, rank:'', grade:'', name: '煙', score:0 , cols: 1, rows: 1},
  { id: 8, difficult:17, rank:'', grade:'', name: 'FLOOR INFECTION Medley from SOUND VOLTEX×jubeat', score:0, cols: 1, rows: 1}, 
  { id: 9, difficult:17, rank:'', grade:'', name: 'Lord=Crossight', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:17, rank:'', grade:'', name: 'Royal Action', score:0 , cols: 1, rows: 1},
  { id: 11, difficult:17, rank:'', grade:'', name: 'Cross Fire', score:0, cols: 1, rows: 1}, 
  { id: 12, difficult:17, rank:'', grade:'', name: 'Life is beautiful', score:0, cols: 1, rows: 1}, 
  { id: 13, difficult:17, rank:'', grade:'', name: 'PIZZATIME', score:0, cols: 1, rows: 1}, 
  { id: 14, difficult:17, rank:'', grade:'', name: 'planetarium', score:0, cols: 1, rows: 1}, 
  { id: 15, difficult:17, rank:'', grade:'', name: 'ゲキツイムラサ', score:0, cols: 1, rows: 1}, 
  { id: 16, difficult:17, rank:'', grade:'', name: 'Lancelot ～Flame of the Rebellion～', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:17, rank:'', grade:'', name: '濁色踊るオートマタ', score:0 , cols: 1, rows: 1},
  { id: 18, difficult:17, rank:'', grade:'', name: 'Tribal Trial', score:0, cols: 1, rows: 1}, 
  { id: 19, difficult:17, rank:'', grade:'', name: 'Poppin’Cats!!', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:17, rank:'', grade:'', name: 'CUTE-Reflection', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:17, rank:'', grade:'', name: '紅の剣舞', score:0, cols: 1, rows: 1}, 
  { id: 22, difficult:17, rank:'', grade:'', name: 'ケロ⑨destiny', score:0, cols: 1, rows: 1}, 
  { id: 23, difficult:17, rank:'', grade:'', name: 'Mayohiga Spurt', score:0, cols: 1, rows: 1}, 
  { id: 24, difficult:17, rank:'', grade:'', name: 'Innocent Floor', score:0, cols: 1, rows: 1}, 
  { id: 25, difficult:17, rank:'', grade:'', name: 'Failnaught', score:0, cols: 1, rows: 1}, 
  { id: 26, difficult:17, rank:'', grade:'', name: 'BEAT-NEW-WORLD', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:17, rank:'', grade:'', name: 'DEADLOCK XXX', score:0 , cols: 1, rows: 1},
  { id: 28, difficult:17, rank:'', grade:'', name: 'ロンロンへ ライライライ！', score:0, cols: 1, rows: 1}, 
  { id: 29, difficult:17, rank:'', grade:'', name: 'Pure Evil', score:0 , cols: 1, rows: 1},
  { id: 30, difficult:17, rank:'', grade:'', name: 'ここからよろしく大作戦143', score:0 , cols: 1, rows: 1},
  { id: 31, difficult:17, rank:'', grade:'', name: 'SPACE VILLAGE', score:0, cols: 1, rows: 1}, 
  { id: 32, difficult:17, rank:'', grade:'', name: 'Double Universe', score:0, cols: 1, rows: 1}, 
  { id: 33, difficult:17, rank:'', grade:'', name: 'キモチコネクト', score:0, cols: 1, rows: 1}, 
  { id: 34, difficult:17, rank:'', grade:'', name: 'Everlasting Message', score:0, cols: 1, rows: 1}, 
  { id: 35, difficult:17, rank:'', grade:'', name: 'V.I.P.', score:0, cols: 1, rows: 1}, 
  { id: 36, difficult:17, rank:'', grade:'', name: 'それは花火のような恋', score:0 , cols: 1, rows: 1},
  { id: 37, difficult:17, rank:'', grade:'', name: 'Hexennacht', score:0 , cols: 1, rows: 1},
  { id: 38, difficult:17, rank:'', grade:'', name: 'Royal Judgement', score:0, cols: 1, rows: 1}, 
  { id: 39, difficult:17, rank:'', grade:'', name: 'Fly Like You', score:0 , cols: 1, rows: 1},
  { id: 40, difficult:17, rank:'', grade:'', name: 'Enter The Fire', score:0 , cols: 1, rows: 1}
]

export const DIFFICULTS_17P2: Difficult[] = [
  { id: 1, difficult:17, rank:'', grade:'', name: 'Made In Love', score:0, cols: 1, rows: 1}, 
  { id: 2, difficult:17, rank:'', grade:'', name: 'Deadly force', score:0, cols: 1, rows: 1}, 
  { id: 3, difficult:17, rank:'', grade:'', name: 'エンゲージ〆ント', score:0, cols: 1, rows: 1}, 
  { id: 4, difficult:17, rank:'', grade:'', name: 'KAC 2012 ULTIMATE MEDLEY -HISTORIA SOUND VOLTEX-', score:0, cols: 1, rows: 1}, 
  { id: 5, difficult:17, rank:'', grade:'', name: 'セイレーン ～悲壮の竪琴～', score:0, cols: 1, rows: 1}, 
  { id: 6, difficult:17, rank:'', grade:'', name: 'Sailing Force', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:17, rank:'', grade:'', name: '幽玄の桜', score:0 , cols: 1, rows: 1},
  { id: 8, difficult:17, rank:'', grade:'', name: 'ぼくらしかしらない', score:0, cols: 1, rows: 1}, 
  { id: 9, difficult:17, rank:'', grade:'', name: 'Xéroa', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:17, rank:'', grade:'', name: 'プレインエイジア(MRM REMIX)', score:0 , cols: 1, rows: 1},
  { id: 11, difficult:17, rank:'', grade:'', name: 'THE凸GENERATOR', score:0, cols: 1, rows: 1}, 
  { id: 12, difficult:17, rank:'', grade:'', name: 'FREEDOM DiVE', score:0, cols: 1, rows: 1}, 
  { id: 13, difficult:17, rank:'', grade:'', name: 'ラキラキ', score:0, cols: 1, rows: 1}, 
  { id: 14, difficult:17, rank:'', grade:'', name: '悪性ロリィタマキャヴェリズム', score:0, cols: 1, rows: 1}, 
  { id: 15, difficult:17, rank:'', grade:'', name: 'Into The Madness', score:0, cols: 1, rows: 1}, 
  { id: 16, difficult:17, rank:'', grade:'', name: 'Jetcoaster Windy', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:17, rank:'', grade:'', name: '真夏の海の修道女', score:0 , cols: 1, rows: 1},
  { id: 18, difficult:17, rank:'', grade:'', name: 'サヨナラ・ヘヴン （かめりあ\'s NEKOMATAelectroRMX）', score:0, cols: 1, rows: 1}, 
  { id: 19, difficult:17, rank:'', grade:'', name: 'アキネイション', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:17, rank:'', grade:'', name: '{albus}', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:17, rank:'', grade:'', name: 'Six String Proof', score:0, cols: 1, rows: 1}, 
  { id: 22, difficult:17, rank:'', grade:'', name: 'infinite:youniverse', score:0, cols: 1, rows: 1}, 
  { id: 23, difficult:17, rank:'', grade:'', name: '雪女', score:0, cols: 1, rows: 1}, 
  { id: 24, difficult:17, rank:'', grade:'', name: 'イグジスタンス', score:0, cols: 1, rows: 1}, 
  { id: 25, difficult:17, rank:'', grade:'', name: 'Virtual Bit', score:0, cols: 1, rows: 1}, 
  { id: 26, difficult:17, rank:'', grade:'', name: 'Blue Forest (Prog Keys Remix)', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:17, rank:'', grade:'', name: 'カミサマネジマキ', score:0 , cols: 1, rows: 1},
  { id: 28, difficult:17, rank:'', grade:'', name: 'Xroniàl Xéro', score:0, cols: 1, rows: 1}, 
  { id: 29, difficult:17, rank:'', grade:'', name: 'セツナトリップ', score:0 , cols: 1, rows: 1},
  { id: 30, difficult:17, rank:'', grade:'', name: 'IX', score:0 , cols: 1, rows: 1},
  { id: 31, difficult:17, rank:'', grade:'', name: 'ALBIDA Powerless Mix', score:0, cols: 1, rows: 1}, 
  { id: 32, difficult:17, rank:'', grade:'', name: 'Sunflower Vibes', score:0, cols: 1, rows: 1}, 
  { id: 33, difficult:17, rank:'', grade:'', name: 'REGALIA', score:0, cols: 1, rows: 1}, 
  { id: 34, difficult:17, rank:'', grade:'', name: 'Chocolate Planet', score:0, cols: 1, rows: 1}, 
  { id: 35, difficult:17, rank:'', grade:'', name: '僕らの時間', score:0, cols: 1, rows: 1}, 
  { id: 36, difficult:17, rank:'', grade:'', name: 'True Blue', score:0 , cols: 1, rows: 1},
  { id: 37, difficult:17, rank:'', grade:'', name: 'Screaming!!', score:0 , cols: 1, rows: 1},
  { id: 38, difficult:17, rank:'', grade:'', name: '孤月群雲に沈む', score:0, cols: 1, rows: 1}, 
  { id: 39, difficult:17, rank:'', grade:'', name: 'Gimme dreamin\'', score:0 , cols: 1, rows: 1},
  { id: 40, difficult:17, rank:'', grade:'', name: 'ABSOLUTE(ismK passionate remix)', score:0 , cols: 1, rows: 1}
]


export const DIFFICULTS_17P1: Difficult[] = [
  { id: 1, difficult:17, rank:'', grade:'', name: 'Max Burning!!', score:0, cols: 1, rows: 1}, 
  { id: 2, difficult:17, rank:'', grade:'', name: 'チルノとまりおのパーフェクトさんすう教室', score:0, cols: 1, rows: 1}, 
  { id: 3, difficult:17, rank:'', grade:'', name: '物凄いスペースシャトルでこいしが物凄いうた', score:0, cols: 1, rows: 1}, 
  { id: 4, difficult:17, rank:'', grade:'', name: 'MilK', score:0, cols: 1, rows: 1}, 
  { id: 5, difficult:17, rank:'', grade:'', name: 'メルヘン風紀委員会', score:0, cols: 1, rows: 1}, 
  { id: 6, difficult:17, rank:'', grade:'', name: '夏色DIARY -Summer Dazzlin\' Vacation miX-', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:17, rank:'', grade:'', name: 'DIABLOSIS::Nāga', score:0 , cols: 1, rows: 1},
  { id: 8, difficult:17, rank:'', grade:'', name: 'Follow Up', score:0, cols: 1, rows: 1}, 
  { id: 9, difficult:17, rank:'', grade:'', name: 'Parousia', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:17, rank:'', grade:'', name: 'BELOBOG', score:0 , cols: 1, rows: 1},
  { id: 11, difficult:17, rank:'', grade:'', name: 'ЯeviveR', score:0, cols: 1, rows: 1}, 
  { id: 12, difficult:17, rank:'', grade:'', name: 'BLAZE∞BREEZE', score:0, cols: 1, rows: 1}, 
  { id: 13, difficult:17, rank:'', grade:'', name: 'Paradission', score:0, cols: 1, rows: 1}, 
  { id: 14, difficult:17, rank:'', grade:'', name: 'Booths of Fighters', score:0, cols: 1, rows: 1}, 
  { id: 15, difficult:17, rank:'', grade:'', name: 'The Sampling Paradise (P*Light Remix)', score:0, cols: 1, rows: 1}, 
  { id: 16, difficult:17, rank:'', grade:'', name: 'ULTRA B+K', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:17, rank:'', grade:'', name: 'Time to Air -Fly High Remix-', score:0 , cols: 1, rows: 1},
  { id: 18, difficult:17, rank:'', grade:'', name: 'Redshift 2nd Ignition', score:0, cols: 1, rows: 1}, 
  { id: 19, difficult:17, rank:'', grade:'', name: 'Erlung', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:17, rank:'', grade:'', name: 'Blue Stream', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:17, rank:'', grade:'', name: '患部で止まってすぐ溶ける ～ 狂気の優曇華院', score:0, cols: 1, rows: 1}, 
  { id: 22, difficult:17, rank:'', grade:'', name: 'Revolution', score:0, cols: 1, rows: 1}, 
  { id: 23, difficult:17, rank:'', grade:'', name: 'INFINITY OVERDRIVE', score:0, cols: 1, rows: 1}, 
  { id: 24, difficult:17, rank:'', grade:'', name: 'S1CK_F41RY', score:0, cols: 1, rows: 1}, 
  { id: 25, difficult:17, rank:'', grade:'', name: '柳の下のデュラハン hard chaos mix', score:0, cols: 1, rows: 1}, 
  { id: 26, difficult:17, rank:'', grade:'', name: 'Rebellio', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:17, rank:'', grade:'', name: '50th Memorial Songs -The BEMANI History-', score:0 , cols: 1, rows: 1},
  { id: 28, difficult:17, rank:'', grade:'', name: 'sink into the dream', score:0, cols: 1, rows: 1}, 
  { id: 29, difficult:17, rank:'', grade:'', name: 'Calamity Tempest', score:0 , cols: 1, rows: 1},
  { id: 30, difficult:17, rank:'', grade:'', name: 'Vigor', score:0 , cols: 1, rows: 1},
  { id: 31, difficult:17, rank:'', grade:'', name: 'ぼくらの16bit戦争', score:0, cols: 1, rows: 1}, 
  { id: 32, difficult:17, rank:'', grade:'', name: '蓬莱フェスティボー', score:0, cols: 1, rows: 1}, 
  { id: 33, difficult:17, rank:'', grade:'', name: '3y3s (JMBS FUNKOT RMX)', score:0, cols: 1, rows: 1}, 
  { id: 34, difficult:17, rank:'', grade:'', name: 'Metamorphobia', score:0, cols: 1, rows: 1}, 
  { id: 35, difficult:17, rank:'', grade:'', name: 'If', score:0, cols: 1, rows: 1}, 
  { id: 36, difficult:17, rank:'', grade:'', name: 'onslaught -Retaliation of Bahamūt-', score:0 , cols: 1, rows: 1},
  { id: 37, difficult:17, rank:'', grade:'', name: 'ABSOLUTE (saminun mix)', score:0 , cols: 1, rows: 1},
  { id: 38, difficult:17, rank:'', grade:'', name: 'SHION -sublimation mix-', score:0, cols: 1, rows: 1}, 
  { id: 39, difficult:17, rank:'', grade:'', name: '月下の舞兎祭', score:0 , cols: 1, rows: 1},
  { id: 40, difficult:17, rank:'', grade:'', name: 'Iridescent Clouds', score:0 , cols: 1, rows: 1},
  { id: 41, difficult:17, rank:'', grade:'', name: 'Fun walk!!', score:0, cols: 1, rows: 1}, 
  { id: 42, difficult:17, rank:'', grade:'', name: 'Verstärkt Killer', score:0, cols: 1, rows: 1}, 
  { id: 43, difficult:17, rank:'', grade:'', name: 'Whip☆Drip', score:0, cols: 1, rows: 1}, 
  { id: 44, difficult:17, rank:'', grade:'', name: '木漏れ日に咲く', score:0, cols: 1, rows: 1}, 
  { id: 45, difficult:17, rank:'', grade:'', name: 'Devastated Territory', score:0, cols: 1, rows: 1}
]


export const DIFFICULTS_17P0: Difficult[] = [
  { id: 1, difficult:17, rank:'', grade:'', name: 'cloud', score:0, cols: 1, rows: 1}, 
  { id: 2, difficult:17, rank:'', grade:'', name: 'Daisycutter', score:0, cols: 1, rows: 1}, 
  { id: 3, difficult:17, rank:'', grade:'', name: 'Altale', score:0, cols: 1, rows: 1}, 
  { id: 4, difficult:17, rank:'', grade:'', name: 'バンブーソード・ガール', score:0, cols: 1, rows: 1}, 
  { id: 5, difficult:17, rank:'', grade:'', name: 'じゅーじゅー♥焼肉の火からフェニックス！？～再誕の†炭火焼き～', score:0, cols: 1, rows: 1}, 
  { id: 6, difficult:17, rank:'', grade:'', name: 'Afterimage d\'automne', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:17, rank:'', grade:'', name: 'B.B.K.K.B.K.K.', score:0 , cols: 1, rows: 1},
  { id: 8, difficult:17, rank:'', grade:'', name: 'take a step forward', score:0, cols: 1, rows: 1}, 
  { id: 9, difficult:17, rank:'', grade:'', name: 'ΛΛemoria', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:17, rank:'', grade:'', name: 'Inixia', score:0 , cols: 1, rows: 1},
  { id: 11, difficult:17, rank:'', grade:'', name: 'Distorted Floor', score:0, cols: 1, rows: 1}, 
  { id: 12, difficult:17, rank:'', grade:'', name: '鬼天', score:0, cols: 1, rows: 1}, 
  { id: 13, difficult:17, rank:'', grade:'', name: 'Grand Chariot', score:0, cols: 1, rows: 1}, 
  { id: 14, difficult:17, rank:'', grade:'', name: '色を喪った街', score:0, cols: 1, rows: 1}, 
  { id: 15, difficult:17, rank:'', grade:'', name: 'Sacrifice Escape: 不条理の模倣による感情と代償', score:0, cols: 1, rows: 1}, 
  { id: 16, difficult:17, rank:'', grade:'', name: 'Heavenly Adventure', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:17, rank:'', grade:'', name: 'Twilight ∞ nighT', score:0 , cols: 1, rows: 1},
  { id: 18, difficult:17, rank:'', grade:'', name: 'Mischievous theater', score:0, cols: 1, rows: 1}, 
  { id: 19, difficult:17, rank:'', grade:'', name: 'Colorless feat.ももかみ', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:17, rank:'', grade:'', name: 'CENSORED!!', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:17, rank:'', grade:'', name: 'Rejoin', score:0, cols: 1, rows: 1}, 
  { id: 22, difficult:17, rank:'', grade:'', name: 'Wish upon Twin Stars', score:0, cols: 1, rows: 1}, 
  { id: 23, difficult:17, rank:'', grade:'', name: 'ウバワレ', score:0, cols: 1, rows: 1}, 
  { id: 24, difficult:17, rank:'', grade:'', name: 'Backflow', score:0, cols: 1, rows: 1}, 
  { id: 25, difficult:17, rank:'', grade:'', name: 'KiLLeR MeRMaiD', score:0, cols: 1, rows: 1}, 
  { id: 26, difficult:17, rank:'', grade:'', name: 'Emperor\'s Divide', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:17, rank:'', grade:'', name: '悪戯センセーション', score:0 , cols: 1, rows: 1},
  { id: 28, difficult:17, rank:'', grade:'', name: 'Zero-Day Exploit', score:0, cols: 1, rows: 1}, 
  { id: 29, difficult:17, rank:'', grade:'', name: 'あれこれそれどれ', score:0 , cols: 1, rows: 1},
  { id: 30, difficult:17, rank:'', grade:'', name: 'Never Fails', score:0 , cols: 1, rows: 1},
  { id: 31, difficult:17, rank:'', grade:'', name: '熱情のサパデアード', score:0, cols: 1, rows: 1}, 
  { id: 32, difficult:17, rank:'', grade:'', name: 'ハレ晴レユカイ／アニメ「涼宮ハルヒの憂鬱」より', score:0, cols: 1, rows: 1}, 
  { id: 33, difficult:17, rank:'', grade:'', name: 'No way', score:0, cols: 1, rows: 1}, 
  { id: 34, difficult:17, rank:'', grade:'', name: '405nm(Shu※mix)', score:0, cols: 1, rows: 1}, 
  { id: 35, difficult:17, rank:'', grade:'', name: 'clear:wings', score:0, cols: 1, rows: 1}, 
  { id: 36, difficult:17, rank:'', grade:'', name: 'Sakura Fubuki', score:0 , cols: 1, rows: 1},
  { id: 37, difficult:17, rank:'', grade:'', name: '777', score:0 , cols: 1, rows: 1},
  { id: 38, difficult:17, rank:'', grade:'', name: 'Impress(siqlo\'s Hi-Tech Veats)', score:0, cols: 1, rows: 1}, 
  { id: 39, difficult:17, rank:'', grade:'', name: 'Blue Forest(NightBouncebRemix)', score:0 , cols: 1, rows: 1},
  { id: 40, difficult:17, rank:'', grade:'', name: 'Help me, ERINNNNNN!! #幻想郷ホロイズムver.', score:0 , cols: 1, rows: 1},
  { id: 41, difficult:17, rank:'', grade:'', name: '響く静寂', score:0, cols: 1, rows: 1}, 
  { id: 42, difficult:17, rank:'', grade:'', name: '恋獄対刃', score:0, cols: 1, rows: 1}, 
  { id: 43, difficult:17, rank:'', grade:'', name: '運命超過乃巡合', score:0, cols: 1, rows: 1}, 
  { id: 44, difficult:17, rank:'', grade:'', name: '叛逆のディスパレート', score:0, cols: 1, rows: 1}, 
  { id: 45, difficult:17, rank:'', grade:'', name: 'キラメキ居残り大戦争', score:0, cols: 1, rows: 1}
]


export const DIFFICULTS_17M1: Difficult[] = [
  { id: 1, difficult:17, rank:'', grade:'', name: 'Innocent Tempest', score:0, cols: 1, rows: 1}, 
  { id: 2, difficult:17, rank:'', grade:'', name: 'Awakening', score:0, cols: 1, rows: 1}, 
  { id: 3, difficult:17, rank:'', grade:'', name: '朱と碧のランページ', score:0, cols: 1, rows: 1}, 
  { id: 4, difficult:17, rank:'', grade:'', name: 'Fire Strike', score:0, cols: 1, rows: 1}, 
  { id: 5, difficult:17, rank:'', grade:'', name: 'もってけ！セーラーふく／アニメ「らき☆すた」より', score:0, cols: 1, rows: 1}, 
  { id: 6, difficult:17, rank:'', grade:'', name: 'Sparkle Smilin\'', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:17, rank:'', grade:'', name: 'EDEN of TRUTH', score:0 , cols: 1, rows: 1},
  { id: 8, difficult:17, rank:'', grade:'', name: 'Space Diver Tama', score:0, cols: 1, rows: 1}, 
  { id: 9, difficult:17, rank:'', grade:'', name: 'BLACK JACKAL', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:17, rank:'', grade:'', name: 'TIEFSEE', score:0 , cols: 1, rows: 1},
  { id: 11, difficult:17, rank:'', grade:'', name: 'Record one\'s Dream', score:0, cols: 1, rows: 1}, 
  { id: 12, difficult:17, rank:'', grade:'', name: '#FairyJoke #SDVX_Edit', score:0, cols: 1, rows: 1}, 
  { id: 13, difficult:17, rank:'', grade:'', name: 'Junk Mania', score:0, cols: 1, rows: 1}, 
  { id: 14, difficult:17, rank:'', grade:'', name: 'Discloze', score:0, cols: 1, rows: 1}, 
  { id: 15, difficult:17, rank:'', grade:'', name: 'シープドリーミン', score:0, cols: 1, rows: 1}, 
  { id: 16, difficult:17, rank:'', grade:'', name: 'Believe (y)our Wings {V:IVID RAYS}', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:17, rank:'', grade:'', name: 'Chocolate Parade', score:0 , cols: 1, rows: 1},
  { id: 18, difficult:17, rank:'', grade:'', name: '十面相', score:0, cols: 1, rows: 1}, 
  { id: 19, difficult:17, rank:'', grade:'', name: 'FIRE FIRE -DARK BLAZE REMIX-', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:17, rank:'', grade:'', name: 'VIVID DEBUT!', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:17, rank:'', grade:'', name: '黎明スケッチブック', score:0, cols: 1, rows: 1}, 
  { id: 22, difficult:17, rank:'', grade:'', name: 'Far Away', score:0, cols: 1, rows: 1}, 
  { id: 23, difficult:17, rank:'', grade:'', name: '感情の魔天楼 ～ Arr.Demetori', score:0, cols: 1, rows: 1}, 
  { id: 24, difficult:17, rank:'', grade:'', name: 'Hoshizora Illumination', score:0, cols: 1, rows: 1}, 
  { id: 25, difficult:17, rank:'', grade:'', name: 'FIRE FIRE(Kazmasa Remix)', score:0, cols: 1, rows: 1}, 
  { id: 26, difficult:17, rank:'', grade:'', name: 'SUPER BUBBLE JOURNEY', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:17, rank:'', grade:'', name: 'Little princess has no identity.', score:0 , cols: 1, rows: 1},
  { id: 28, difficult:17, rank:'', grade:'', name: 'F.K.S.', score:0, cols: 1, rows: 1}, 
  { id: 29, difficult:17, rank:'', grade:'', name: 'EGG', score:0 , cols: 1, rows: 1},
  { id: 30, difficult:17, rank:'', grade:'', name: 'Justitia Gladius', score:0 , cols: 1, rows: 1},
  { id: 31, difficult:17, rank:'', grade:'', name: '無気力クーデター', score:0, cols: 1, rows: 1}, 
  { id: 32, difficult:17, rank:'', grade:'', name: 'Princess Lily', score:0, cols: 1, rows: 1}, 
  { id: 33, difficult:17, rank:'', grade:'', name: 'UROBØROS', score:0, cols: 1, rows: 1}, 
  { id: 34, difficult:17, rank:'', grade:'', name: 'CUTIE☆EX-DREAM', score:0, cols: 1, rows: 1}, 
  { id: 35, difficult:17, rank:'', grade:'', name: 'The star in eclipse', score:0, cols: 1, rows: 1}, 
  { id: 36, difficult:17, rank:'', grade:'', name: 'Believe (y)our Wings {GRA5P WAVES}', score:0 , cols: 1, rows: 1},
  { id: 37, difficult:17, rank:'', grade:'', name: 'Hellfire', score:0 , cols: 1, rows: 1},
  { id: 38, difficult:17, rank:'', grade:'', name: 'Stleq', score:0, cols: 1, rows: 1}, 
  { id: 39, difficult:17, rank:'', grade:'', name: '信仰は儚き人間の為に ～ Arr.Demetori', score:0 , cols: 1, rows: 1},
  { id: 40, difficult:17, rank:'', grade:'', name: '常夏！！クリスタライズ・シャーベット', score:0 , cols: 1, rows: 1},
  { id: 41, difficult:17, rank:'', grade:'', name: '太陽曰く燃えよカオス（Sol oscuro ¡Nya! Mix）', score:0, cols: 1, rows: 1}, 
  { id: 42, difficult:17, rank:'', grade:'', name: 'Lost wing at.0', score:0, cols: 1, rows: 1}, 
  { id: 43, difficult:17, rank:'', grade:'', name: 'Holy Legacy', score:0, cols: 1, rows: 1}, 
  { id: 44, difficult:17, rank:'', grade:'', name: '門門しましょ', score:0, cols: 1, rows: 1}, 
  { id: 45, difficult:17, rank:'', grade:'', name: 'オルターエゴ', score:0, cols: 1, rows: 1},
  { id: 46, difficult:17, rank:'', grade:'', name: 'Xymatic Scope', score:0, cols: 1, rows: 1}
]


export const DIFFICULTS_17M2: Difficult[] = [
  { id: 1, difficult:17, rank:'', grade:'', name: '廃獄ドリームランド', score:0, cols: 1, rows: 1}, 
  { id: 2, difficult:17, rank:'', grade:'', name: 'ふ・れ・ん・ど・し・た・い（WEREHEREMIX)', score:0, cols: 1, rows: 1}, 
  { id: 3, difficult:17, rank:'', grade:'', name: 'éclair au chocolat', score:0, cols: 1, rows: 1}, 
  { id: 4, difficult:17, rank:'', grade:'', name: 'The First Step', score:0, cols: 1, rows: 1}, 
  { id: 5, difficult:17, rank:'', grade:'', name: '零次元エクスプレス', score:0, cols: 1, rows: 1}, 
  { id: 6, difficult:17, rank:'', grade:'', name: 'Clash of swords', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:17, rank:'', grade:'', name: '逆さま♥シンデレラパレード', score:0 , cols: 1, rows: 1},
  { id: 8, difficult:17, rank:'', grade:'', name: '†:OLPHEUX:†', score:0, cols: 1, rows: 1}, 
  { id: 9, difficult:17, rank:'', grade:'', name: 'Quark', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:17, rank:'', grade:'', name: 'Melty Sweets', score:0 , cols: 1, rows: 1},
  { id: 11, difficult:17, rank:'', grade:'', name: 'イゴモヨス＝オムルのテーマによるブヨブヨ・スケッチの試み', score:0, cols: 1, rows: 1}, 
  { id: 12, difficult:17, rank:'', grade:'', name: '少女暴動', score:0, cols: 1, rows: 1}, 
  { id: 13, difficult:17, rank:'', grade:'', name: 'ΩBIRD', score:0, cols: 1, rows: 1}, 
  { id: 14, difficult:17, rank:'', grade:'', name: 'ストリーミングハート', score:0, cols: 1, rows: 1}, 
  { id: 15, difficult:17, rank:'', grade:'', name: 'ultra turbo', score:0, cols: 1, rows: 1}, 
  { id: 16, difficult:17, rank:'', grade:'', name: 'ケムマキunderground', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:17, rank:'', grade:'', name: 'ようこそジャパリパークへ／アニメ「けものフレンズ」より', score:0 , cols: 1, rows: 1},
  { id: 18, difficult:17, rank:'', grade:'', name: 'Sulk', score:0, cols: 1, rows: 1}, 
  { id: 19, difficult:17, rank:'', grade:'', name: 'WONDER_WOBBLER', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:17, rank:'', grade:'', name: '過食性:アイドル症候群', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:17, rank:'', grade:'', name: 'Coldlapse', score:0, cols: 1, rows: 1}, 
  { id: 22, difficult:17, rank:'', grade:'', name: '轟け！恋のビーンボール！！', score:0, cols: 1, rows: 1}, 
  { id: 23, difficult:17, rank:'', grade:'', name: 'Destruction & Qreation', score:0, cols: 1, rows: 1}, 
  { id: 24, difficult:17, rank:'', grade:'', name: 'PIERROT KNIfE', score:0, cols: 1, rows: 1}, 
  { id: 25, difficult:17, rank:'', grade:'', name: 'cobalt', score:0, cols: 1, rows: 1}, 
  { id: 26, difficult:17, rank:'', grade:'', name: 'Inscape', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:17, rank:'', grade:'', name: 'Game Over', score:0 , cols: 1, rows: 1},
  { id: 28, difficult:17, rank:'', grade:'', name: 'Rubeus', score:0, cols: 1, rows: 1}, 
  { id: 29, difficult:17, rank:'', grade:'', name: 'BLIZZARD BEAT', score:0 , cols: 1, rows: 1},
  { id: 30, difficult:17, rank:'', grade:'', name: 'Carry Me Away', score:0 , cols: 1, rows: 1},
  { id: 31, difficult:17, rank:'', grade:'', name: 'ABSOLUTE (EUROBEAT REMIX)', score:0, cols: 1, rows: 1}, 
  { id: 32, difficult:17, rank:'', grade:'', name: 'ロプノールの商隊', score:0, cols: 1, rows: 1}, 
  { id: 33, difficult:17, rank:'', grade:'', name: 'おーまい！らぶりー！すうぃーてぃ！だーりん！', score:0, cols: 1, rows: 1}, 
  { id: 34, difficult:17, rank:'', grade:'', name: '御千手メディテーション', score:0, cols: 1, rows: 1}, 
  { id: 35, difficult:17, rank:'', grade:'', name: 'VIVIDWAVERS', score:0, cols: 1, rows: 1}, 
  { id: 36, difficult:17, rank:'', grade:'', name: 'すろぉもぉしょん', score:0 , cols: 1, rows: 1},
  { id: 37, difficult:17, rank:'', grade:'', name: 'ラブキラ☆スプラッシュ', score:0 , cols: 1, rows: 1},
  { id: 38, difficult:17, rank:'', grade:'', name: 'Another Chapter', score:0, cols: 1, rows: 1}, 
  { id: 39, difficult:17, rank:'', grade:'', name: 'NEON LOVE♥POTION!!!', score:0 , cols: 1, rows: 1},
  { id: 40, difficult:17, rank:'', grade:'', name: 'Dark Matter', score:0 , cols: 1, rows: 1},
  { id: 41, difficult:17, rank:'', grade:'', name: 'Secret Traveler -MeniRemix-', score:0, cols: 1, rows: 1}, 
  { id: 42, difficult:17, rank:'', grade:'', name: 'Dharma', score:0, cols: 1, rows: 1}, 
  { id: 43, difficult:17, rank:'', grade:'', name: 'floorkiller', score:0, cols: 1, rows: 1}, 
  { id: 44, difficult:17, rank:'', grade:'', name: 'GODHEART', score:0, cols: 1, rows: 1}, 
  { id: 45, difficult:17, rank:'', grade:'', name: 'トラダンスアナーキー', score:0, cols: 1, rows: 1}
]


export const DIFFICULTS_17M3: Difficult[] = [
  { id: 1, difficult:17, rank:'', grade:'', name: 'ЯegreT of MemoRy', score:0, cols: 1, rows: 1}, 
  { id: 2, difficult:17, rank:'', grade:'', name: '遷', score:0, cols: 1, rows: 1}, 
  { id: 3, difficult:17, rank:'', grade:'', name: 'DO-IT-AMA-SITE!!!', score:0, cols: 1, rows: 1}, 
  { id: 4, difficult:17, rank:'', grade:'', name: '君は Fantasista', score:0, cols: 1, rows: 1}, 
  { id: 5, difficult:17, rank:'', grade:'', name: 'TYCOON', score:0, cols: 1, rows: 1}, 
  { id: 6, difficult:17, rank:'', grade:'', name: 'choux à la crème', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:17, rank:'', grade:'', name: '大宇宙ステージ', score:0 , cols: 1, rows: 1},
  { id: 8, difficult:17, rank:'', grade:'', name: 'Appliqué', score:0, cols: 1, rows: 1}, 
  { id: 9, difficult:17, rank:'', grade:'', name: 'デュアルメモリ', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:17, rank:'', grade:'', name: 'DESIRE', score:0 , cols: 1, rows: 1},
  { id: 11, difficult:17, rank:'', grade:'', name: '御伽噺に幕切れを', score:0, cols: 1, rows: 1}, 
  { id: 12, difficult:17, rank:'', grade:'', name: 'Invisible Bullets', score:0, cols: 1, rows: 1}, 
  { id: 13, difficult:17, rank:'', grade:'', name: 'きらきらタイム☆', score:0, cols: 1, rows: 1}, 
  { id: 14, difficult:17, rank:'', grade:'', name: 'Borealis', score:0, cols: 1, rows: 1}, 
  { id: 15, difficult:17, rank:'', grade:'', name: 'empty', score:0, cols: 1, rows: 1}, 
  { id: 16, difficult:17, rank:'', grade:'', name: 'Knights Assault', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:17, rank:'', grade:'', name: '焔 -MAGMA-', score:0 , cols: 1, rows: 1},
  { id: 18, difficult:17, rank:'', grade:'', name: 'Adrenaline Rush', score:0, cols: 1, rows: 1}, 
  { id: 19, difficult:17, rank:'', grade:'', name: 'HEAVENLY SMILE', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:17, rank:'', grade:'', name: 'Idola', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:17, rank:'', grade:'', name: 'Finale', score:0, cols: 1, rows: 1}, 
  { id: 22, difficult:17, rank:'', grade:'', name: 'Xibercannon', score:0, cols: 1, rows: 1}, 
  { id: 23, difficult:17, rank:'', grade:'', name: 'Arcade Prison', score:0, cols: 1, rows: 1}, 
  { id: 24, difficult:17, rank:'', grade:'', name: 'Elemental Creation', score:0, cols: 1, rows: 1}, 
  { id: 25, difficult:17, rank:'', grade:'', name: 'Staring at star', score:0, cols: 1, rows: 1}, 
  { id: 26, difficult:17, rank:'', grade:'', name: 'β', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:17, rank:'', grade:'', name: 'Apex of the World', score:0 , cols: 1, rows: 1},
  { id: 28, difficult:17, rank:'', grade:'', name: 'VOLTEXES IV', score:0, cols: 1, rows: 1}, 
  { id: 29, difficult:17, rank:'', grade:'', name: '.59 -BOOTH BOOST REMIX-', score:0 , cols: 1, rows: 1},
  { id: 30, difficult:17, rank:'', grade:'', name: '120秒のエンドロール', score:0 , cols: 1, rows: 1},
  { id: 31, difficult:17, rank:'', grade:'', name: 'Tic Exe', score:0, cols: 1, rows: 1}, 
  { id: 32, difficult:17, rank:'', grade:'', name: 'Lucky*Clover', score:0, cols: 1, rows: 1}, 
  { id: 33, difficult:17, rank:'', grade:'', name: 'POSSESSION(Gowrock Remix)', score:0, cols: 1, rows: 1}, 
  { id: 34, difficult:17, rank:'', grade:'', name: 'Synergy For Angels', score:0, cols: 1, rows: 1}, 
  { id: 35, difficult:17, rank:'', grade:'', name: '断罪は遍く人間の元に', score:0, cols: 1, rows: 1}, 
  { id: 36, difficult:17, rank:'', grade:'', name: '零の位相', score:0 , cols: 1, rows: 1},
  { id: 37, difficult:17, rank:'', grade:'', name: 'The setting sun', score:0 , cols: 1, rows: 1},
  { id: 38, difficult:17, rank:'', grade:'', name: 'ANTI THE∞HOLiC', score:0, cols: 1, rows: 1}, 
  { id: 39, difficult:17, rank:'', grade:'', name: 'AXION', score:0 , cols: 1, rows: 1},
  { id: 40, difficult:17, rank:'', grade:'', name: 'CLOUDS FLYER -sdvx edit-', score:0 , cols: 1, rows: 1},
  { id: 41, difficult:17, rank:'', grade:'', name: 'JULIAN', score:0, cols: 1, rows: 1}, 
  { id: 42, difficult:17, rank:'', grade:'', name: 'ベビーステップ', score:0, cols: 1, rows: 1}, 
  { id: 43, difficult:17, rank:'', grade:'', name: 'Rebuilding of Paradise Lost', score:0, cols: 1, rows: 1}, 
  { id: 44, difficult:17, rank:'', grade:'', name: 'Fáfnir', score:0, cols: 1, rows: 1}, 
  { id: 45, difficult:17, rank:'', grade:'', name: 'D1g1t1ze b0dy', score:0, cols: 1, rows: 1},
  { id: 46, difficult:17, rank:'', grade:'', name: 'WILD FIRE', score:0, cols: 1, rows: 1}
]


export const DIFFICULTS_17M4: Difficult[] = [
  { id: 1, difficult:17, rank:'', grade:'', name: 'INDEPENDENT SKY', score:0, cols: 1, rows: 1}, 
  { id: 2, difficult:17, rank:'', grade:'', name: 'cross the future', score:0, cols: 1, rows: 1}, 
  { id: 3, difficult:17, rank:'', grade:'', name: 'アワデコノヨヲ', score:0, cols: 1, rows: 1}, 
  { id: 4, difficult:17, rank:'', grade:'', name: '革命パッショネイト', score:0, cols: 1, rows: 1}, 
  { id: 5, difficult:17, rank:'', grade:'', name: 'ブチ上げ候！現代忍者三姉妹', score:0, cols: 1, rows: 1}, 
  { id: 6, difficult:17, rank:'', grade:'', name: 'Chaotic Romance', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:17, rank:'', grade:'', name: 'ボルテ体操第一', score:0 , cols: 1, rows: 1},
  { id: 8, difficult:17, rank:'', grade:'', name: 'Harmonia', score:0, cols: 1, rows: 1}, 
  { id: 9, difficult:17, rank:'', grade:'', name: 'Twin Rocket', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:17, rank:'', grade:'', name: '伊邪那美白山姫大神', score:0 , cols: 1, rows: 1},
  { id: 11, difficult:17, rank:'', grade:'', name: 'Liévre -blanche-', score:0, cols: 1, rows: 1}, 
  { id: 12, difficult:17, rank:'', grade:'', name: 'Wheel', score:0, cols: 1, rows: 1}, 
  { id: 13, difficult:17, rank:'', grade:'', name: '天ノ弱', score:0, cols: 1, rows: 1}, 
  { id: 14, difficult:17, rank:'', grade:'', name: '幻想系世界修復少女', score:0, cols: 1, rows: 1}, 
  { id: 15, difficult:17, rank:'', grade:'', name: 'DEEP PSYCHEDELIC STRIKER', score:0, cols: 1, rows: 1}, 
  { id: 16, difficult:17, rank:'', grade:'', name: 'Empathetic', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:17, rank:'', grade:'', name: 'イカサマライフゲイム', score:0 , cols: 1, rows: 1},
  { id: 18, difficult:17, rank:'', grade:'', name: '人生リセットボタン', score:0, cols: 1, rows: 1}, 
  { id: 19, difficult:17, rank:'', grade:'', name: 'Happy Sensation', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:17, rank:'', grade:'', name: 'Impress (bansou Remix)', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:17, rank:'', grade:'', name: 'Voltage Higher', score:0, cols: 1, rows: 1}, 
  { id: 22, difficult:17, rank:'', grade:'', name: 'Trill auf G', score:0, cols: 1, rows: 1}, 
  { id: 23, difficult:17, rank:'', grade:'', name: '真夏の蜜と唇 fm. 希望の星は青霄に昇る', score:0, cols: 1, rows: 1}, 
  { id: 24, difficult:17, rank:'', grade:'', name: 'akasha-assembly', score:0, cols: 1, rows: 1}, 
  { id: 25, difficult:17, rank:'', grade:'', name: 'Drizzly Venom', score:0, cols: 1, rows: 1}, 
  { id: 26, difficult:17, rank:'', grade:'', name: '雲海', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:17, rank:'', grade:'', name: 'MARENOL', score:0 , cols: 1, rows: 1},
  { id: 28, difficult:17, rank:'', grade:'', name: '銃弾は解を撃ち抜いて', score:0, cols: 1, rows: 1}, 
  { id: 29, difficult:17, rank:'', grade:'', name: '放課後ストライド', score:0 , cols: 1, rows: 1},
  { id: 30, difficult:17, rank:'', grade:'', name: '444', score:0 , cols: 1, rows: 1},
  { id: 31, difficult:17, rank:'', grade:'', name: 'おどりましょうよ！ドラゴンさん ～転生したらゲーム曲でした～', score:0, cols: 1, rows: 1}, 
  { id: 32, difficult:17, rank:'', grade:'', name: '分けるな危険！モモモモモモーイズム', score:0, cols: 1, rows: 1}, 
  { id: 33, difficult:17, rank:'', grade:'', name: 'Dreaming feat.nomico', score:0, cols: 1, rows: 1}, 
  { id: 34, difficult:17, rank:'', grade:'', name: 'ゴーストルール', score:0, cols: 1, rows: 1}, 
  { id: 35, difficult:17, rank:'', grade:'', name: 'Sparkling Laser Beam', score:0, cols: 1, rows: 1},
  { id: 36, difficult:17, rank:'', grade:'', name: '泥の分際で私だけの大切を奪おうだなんて', score:0, cols: 1, rows: 1}
]


export const DIFFICULTS_17M5: Difficult[] = [
  { id: 1, difficult:17, rank:'', grade:'', name: '9TH5IN', score:0, cols: 1, rows: 1}, 
  { id: 2, difficult:17, rank:'', grade:'', name: 'bistro twins☆☆☆', score:0, cols: 1, rows: 1}, 
  { id: 3, difficult:17, rank:'', grade:'', name: 'Mist In Hell', score:0, cols: 1, rows: 1}, 
  { id: 4, difficult:17, rank:'', grade:'', name: 'EGOISM -Rebuild-', score:0, cols: 1, rows: 1}, 
  { id: 5, difficult:17, rank:'', grade:'', name: 'OUTERHEΛVEN', score:0, cols: 1, rows: 1}, 
  { id: 6, difficult:17, rank:'', grade:'', name: 'Last Battalion', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:17, rank:'', grade:'', name: 'Last Resort', score:0 , cols: 1, rows: 1},
  { id: 8, difficult:17, rank:'', grade:'', name: 'Sephirot', score:0, cols: 1, rows: 1}, 
  { id: 9, difficult:17, rank:'', grade:'', name: 'Smoked Turkey Rag', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:17, rank:'', grade:'', name: 'ゆりゆららららゆるゆり大事件（yuzen remix）', score:0 , cols: 1, rows: 1},
  { id: 11, difficult:17, rank:'', grade:'', name: '星座が恋した瞬間を。', score:0, cols: 1, rows: 1}, 
  { id: 12, difficult:17, rank:'', grade:'', name: 'LittleGameStar', score:0, cols: 1, rows: 1}, 
  { id: 13, difficult:17, rank:'', grade:'', name: 'おにいちゃんハイテック', score:0, cols: 1, rows: 1}, 
  { id: 14, difficult:17, rank:'', grade:'', name: '創世ノート', score:0, cols: 1, rows: 1}, 
  { id: 15, difficult:17, rank:'', grade:'', name: 'セイシュンライナー', score:0, cols: 1, rows: 1}, 
  { id: 16, difficult:17, rank:'', grade:'', name: 'BREAKNECK NY☆N! NY★N!', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:17, rank:'', grade:'', name: '炎夏の音', score:0 , cols: 1, rows: 1},
  { id: 18, difficult:17, rank:'', grade:'', name: '祭囃子', score:0, cols: 1, rows: 1}, 
  { id: 19, difficult:17, rank:'', grade:'', name: 'ツキアカリ', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:17, rank:'', grade:'', name: 'AYAKASHI', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:17, rank:'', grade:'', name: '漆黒のスペシャルプリンセスサンデー', score:0, cols: 1, rows: 1}, 
  { id: 22, difficult:17, rank:'', grade:'', name: 'Oriens', score:0, cols: 1, rows: 1}, 
  { id: 23, difficult:17, rank:'', grade:'', name: '鏡面の波（ramble mix）', score:0, cols: 1, rows: 1}, 
  { id: 24, difficult:17, rank:'', grade:'', name: '少女綺想曲 -G.X.N. Remix-', score:0, cols: 1, rows: 1}, 
  { id: 25, difficult:17, rank:'', grade:'', name: 'Technical Master', score:0, cols: 1, rows: 1}, 
  { id: 26, difficult:17, rank:'', grade:'', name: '逆月', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:17, rank:'', grade:'', name: 'Bye or not', score:0 , cols: 1, rows: 1},
  { id: 28, difficult:17, rank:'', grade:'', name: 'ロキ', score:0, cols: 1, rows: 1}, 
  { id: 29, difficult:17, rank:'', grade:'', name: 'バイナリスター', score:0 , cols: 1, rows: 1},
  { id: 30, difficult:17, rank:'', grade:'', name: '穢れなきユーフォリア', score:0 , cols: 1, rows: 1},
]


export const DIFFICULTS_17M6: Difficult[] = [
  { id: 1, difficult:17, rank:'', grade:'', name: 'Lisa-RICCIA', score:0, cols: 1, rows: 1}, 
  { id: 2, difficult:17, rank:'', grade:'', name: 'うさぬこぬんぬんファンタジー！', score:0, cols: 1, rows: 1}, 
  { id: 3, difficult:17, rank:'', grade:'', name: 'odds and ends', score:0, cols: 1, rows: 1}, 
  { id: 4, difficult:17, rank:'', grade:'', name: 'ポメグラネイト', score:0, cols: 1, rows: 1}, 
  { id: 5, difficult:17, rank:'', grade:'', name: 'オンディーヌの泪', score:0, cols: 1, rows: 1}, 
  { id: 6, difficult:17, rank:'', grade:'', name: 'θコトノハθカプセルθ', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:17, rank:'', grade:'', name: 'cloche(といぼっくすうぃんぐ みっくす)', score:0 , cols: 1, rows: 1},
  { id: 8, difficult:17, rank:'', grade:'', name: 'Enjoy This Time', score:0, cols: 1, rows: 1}, 
  { id: 9, difficult:17, rank:'', grade:'', name: '竹取飛翔', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:17, rank:'', grade:'', name: '夢見草奇譚', score:0 , cols: 1, rows: 1},
  { id: 11, difficult:17, rank:'', grade:'', name: '蟲の棲む処', score:0, cols: 1, rows: 1}, 
  { id: 12, difficult:17, rank:'', grade:'', name: 'インビジブル', score:0, cols: 1, rows: 1}, 
  { id: 13, difficult:17, rank:'', grade:'', name: 'toy boxer', score:0, cols: 1, rows: 1}, 
  { id: 14, difficult:17, rank:'', grade:'', name: '水槽のクジラ', score:0, cols: 1, rows: 1}, 
  { id: 15, difficult:17, rank:'', grade:'', name: 'Still Lonesome', score:0, cols: 1, rows: 1}, 
  { id: 16, difficult:17, rank:'', grade:'', name: 'ガヴリールドロップキック／アニメ「ガヴリールドロップアウト」より', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:17, rank:'', grade:'', name: 'ペタ靴と憂夜リムーバー', score:0 , cols: 1, rows: 1},
  { id: 18, difficult:17, rank:'', grade:'', name: 'Triple Counter', score:0, cols: 1, rows: 1}, 
  { id: 19, difficult:17, rank:'', grade:'', name: '失敗作少女', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:17, rank:'', grade:'', name: 'ZEPHYRANTHES', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:17, rank:'', grade:'', name: 'voltississimo', score:0, cols: 1, rows: 1}, 
  { id: 22, difficult:17, rank:'', grade:'', name: 'Pixelated Platform', score:0, cols: 1, rows: 1}, 
  { id: 23, difficult:17, rank:'', grade:'', name: 'Four Leaves', score:0, cols: 1, rows: 1}, 
  { id: 24, difficult:17, rank:'', grade:'', name: 'ヒトリゴト／アニメ「エロマンガ先生」OP', score:0, cols: 1, rows: 1}, 
  { id: 25, difficult:17, rank:'', grade:'', name: 'ボーイミーツ・ブルー', score:0, cols: 1, rows: 1}, 
  { id: 26, difficult:17, rank:'', grade:'', name: 'アンハッピーリフレイン', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:17, rank:'', grade:'', name: 'クレイジークレイジーダンサーズ', score:0 , cols: 1, rows: 1},
  { id: 28, difficult:17, rank:'', grade:'', name: 'ヒミツダイヤル', score:0, cols: 1, rows: 1}, 
  { id: 29, difficult:17, rank:'', grade:'', name: '全力ハッピーライフ', score:0 , cols: 1, rows: 1},
  { id: 30, difficult:17, rank:'', grade:'', name: 'Chronomia', score:0 , cols: 1, rows: 1},
]


export const DIFFICULTS_17M7: Difficult[] = [
  { id: 1, difficult:17, rank:'', grade:'', name: '見世物ライフ', score:0, cols: 1, rows: 1}, 
  { id: 2, difficult:17, rank:'', grade:'', name: 'scary night', score:0, cols: 1, rows: 1}, 
  { id: 3, difficult:17, rank:'', grade:'', name: 'Decoy', score:0, cols: 1, rows: 1}, 
  { id: 4, difficult:17, rank:'', grade:'', name: '片翼のディザイア', score:0, cols: 1, rows: 1}, 
  { id: 5, difficult:17, rank:'', grade:'', name: 'ハレ トキドキ メランコリック', score:0, cols: 1, rows: 1}, 
  { id: 6, difficult:17, rank:'', grade:'', name: 'Phlox', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:17, rank:'', grade:'', name: 'Sleepless days', score:0 , cols: 1, rows: 1},
  { id: 8, difficult:17, rank:'', grade:'', name: 'Sadistic Stabbing', score:0, cols: 1, rows: 1}, 
  { id: 9, difficult:17, rank:'', grade:'', name: 'ANGER of the GOD', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:17, rank:'', grade:'', name: '星の詩', score:0 , cols: 1, rows: 1},
  { id: 11, difficult:17, rank:'', grade:'', name: 'Paradisus-Paradoxum／アニメ「Re:ゼロから始める異世界生活」より', score:0, cols: 1, rows: 1}, 
  { id: 12, difficult:17, rank:'', grade:'', name: 'Chrono Diver -PENDULUMs-', score:0, cols: 1, rows: 1}, 
  { id: 13, difficult:17, rank:'', grade:'', name: 'Apocrypha', score:0, cols: 1, rows: 1}, 
  { id: 14, difficult:17, rank:'', grade:'', name: '近未来百鬼夜行譚～死返之巻～', score:0, cols: 1, rows: 1}, 
  { id: 15, difficult:17, rank:'', grade:'', name: 'ILL-STARRED Diver', score:0, cols: 1, rows: 1}, 
  { id: 16, difficult:17, rank:'', grade:'', name: 'QUAKE', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:17, rank:'', grade:'', name: 'One In A Billion（Hedonist Remix）', score:0 , cols: 1, rows: 1},
  { id: 18, difficult:17, rank:'', grade:'', name: 'CARNIVOROUS', score:0, cols: 1, rows: 1}, 
  { id: 19, difficult:17, rank:'', grade:'', name: 'STYX HELIX（Digi-Rock Remix）', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:17, rank:'', grade:'', name: 'who I am', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:17, rank:'', grade:'', name: 'MICHIZURE', score:0, cols: 1, rows: 1}
]