import { Difficult } from './indicate';


export const DIFFICULTS_18P7: Difficult[] = [
  { id: 1, difficult:18, rank:'', grade:'', name: 'Joyeuse', score:0, cols: 1, rows: 1}, 
  { id: 2, difficult:18, rank:'', grade:'', name: 'Яe:son D\'être', score:0, cols: 1, rows: 1}, 
  { id: 3, difficult:18, rank:'', grade:'', name: '* Erm, could it be a Spatiotemporal ShockWAVE Syndrome...?', score:0, cols: 1, rows: 1}, 
  { id: 4, difficult:18, rank:'', grade:'', name: 'び', score:0, cols: 1, rows: 1}, 
  { id: 5, difficult:18, rank:'', grade:'', name: 'World\'s end', score:0, cols: 1, rows: 1}, 
  { id: 6, difficult:18, rank:'', grade:'', name: 'ツマミ戦隊 タテレンジャー', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:18, rank:'', grade:'', name: 'Venomous Firefly', score:0 , cols: 1, rows: 1}
]

export const DIFFICULTS_18P6: Difficult[] = [
  { id: 1, difficult:18, rank:'', grade:'', name: 'Xronièr', score:0 , cols: 1, rows: 1}, 
  { id: 2, difficult:18, rank:'', grade:'', name: '準備運動', score:0 , cols: 1, rows: 1},
  { id: 3, difficult:18, rank:'', grade:'', name: 'ΩVERSOUL', score:0 , cols: 1, rows: 1},
  { id: 4, difficult:18, rank:'', grade:'', name: '神話に芽吹く', score:0 , cols: 1, rows: 1}, 
  { id: 5, difficult:18, rank:'', grade:'', name: 'JUNKIE FLAVOR', score:0 , cols: 1, rows: 1},
  { id: 6, difficult:18, rank:'', grade:'', name: 'KAC 2013 Empress Side', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:18, rank:'', grade:'', name: 'KAC 2013 Emperor Side', score:0 , cols: 1, rows: 1}, 
  { id: 8, difficult:18, rank:'', grade:'', name: 'Blastix Riotz', score:0 , cols: 1, rows: 1},
  { id: 9, difficult:18, rank:'', grade:'', name: 'Black Emperor', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:18, rank:'', grade:'', name: 'きたさいたま2000', score:0 , cols: 1, rows: 1}, 
  { id: 11, difficult:18, rank:'', grade:'', name: 'キュリオシティ', score:0 , cols: 1, rows: 1},
  { id: 12, difficult:18, rank:'', grade:'', name: 'XHAOS JUDGE', score:0 , cols: 1, rows: 1},
  { id: 13, difficult:18, rank:'', grade:'', name: '混乱少女♥そふらんちゃん!!', score:0 , cols: 1, rows: 1}, 
  { id: 14, difficult:18, rank:'', grade:'', name: 'Last Concerto', score:0 , cols: 1, rows: 1},
  { id: 15, difficult:18, rank:'', grade:'', name: 'INF-B《L-aste-R》', score:0 , cols: 1, rows: 1},
  { id: 16, difficult:18, rank:'', grade:'', name: 'ムーニャポヨポヨスッポコニャーゴ', score:0 , cols: 1, rows: 1}, 
  { id: 17, difficult:18, rank:'', grade:'', name: 'ZEИITH', score:0 , cols: 1, rows: 1},
  { id: 18, difficult:18, rank:'', grade:'', name: '#SpeedyCats', score:0 , cols: 1, rows: 1},
  { id: 19, difficult:18, rank:'', grade:'', name: 'EMPIRE OF FLAME', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:18, rank:'', grade:'', name: '1', score:0 , cols: 1, rows: 1}
]

export const DIFFICULTS_18P5: Difficult[] = [
  { id: 1, difficult:18, rank:'', grade:'', name: 'ARROW RAIN', score:0 , cols: 1, rows: 1}, 
  { id: 2, difficult:18, rank:'', grade:'', name: '超越してしまった彼女と其を生み落した理由', score:0 , cols: 1, rows: 1},
  { id: 3, difficult:18, rank:'', grade:'', name: '祝福の色彩は想い結ぶ君たち迄', score:0 , cols: 1, rows: 1},
  { id: 4, difficult:18, rank:'', grade:'', name: '*Feels Seasickness...*', score:0 , cols: 1, rows: 1}, 
  { id: 5, difficult:18, rank:'', grade:'', name: 'FIN4LE ～終止線の彼方へ～', score:0 , cols: 1, rows: 1},
  { id: 6, difficult:18, rank:'', grade:'', name: 'STULTI', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:18, rank:'', grade:'', name: 'Concertino in Blue', score:0 , cols: 1, rows: 1}, 
  { id: 8, difficult:18, rank:'', grade:'', name: 'MG277', score:0 , cols: 1, rows: 1},
  { id: 9, difficult:18, rank:'', grade:'', name: '魔理沙は大変なものを盗んでいきました', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:18, rank:'', grade:'', name: 'SAMURAI TIGER', score:0 , cols: 1, rows: 1}, 
  { id: 11, difficult:18, rank:'', grade:'', name: 'Legendary Road', score:0 , cols: 1, rows: 1},
  { id: 12, difficult:18, rank:'', grade:'', name: 'Completeness Under Incompleteness', score:0 , cols: 1, rows: 1},
  { id: 13, difficult:18, rank:'', grade:'', name: 'Aerial Fortress', score:0 , cols: 1, rows: 1}, 
  { id: 14, difficult:18, rank:'', grade:'', name: 'pique', score:0 , cols: 1, rows: 1}, 
  { id: 15, difficult:18, rank:'', grade:'', name: 'Xevel', score:0 , cols: 1, rows: 1},
  { id: 16, difficult:18, rank:'', grade:'', name: 'НУМЛ', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:18, rank:'', grade:'', name: 'Re：End of a Dream', score:0 , cols: 1, rows: 1}, 
  { id: 18, difficult:18, rank:'', grade:'', name: 'Mirrorwall', score:0 , cols: 1, rows: 1},
  { id: 19, difficult:18, rank:'', grade:'', name: 'Divine\'s:Bugscript', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:18, rank:'', grade:'', name: 'gigadelic (かめりあ\'s "The TERA" RMX)', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:18, rank:'', grade:'', name: 'Sayonara Planet Wars', score:0 , cols: 1, rows: 1},
  { id: 22, difficult:18, rank:'', grade:'', name: 'Doppelganger', score:0 , cols: 1, rows: 1},
  { id: 23, difficult:18, rank:'', grade:'', name: '1', score:0 , cols: 1, rows: 1}, 
  { id: 24, difficult:18, rank:'', grade:'', name: 'SAtAN', score:0 , cols: 1, rows: 1}, 
  { id: 25, difficult:18, rank:'', grade:'', name: 'Scars of FAUNA(ろひ Remix)', score:0 , cols: 1, rows: 1},
  { id: 26, difficult:18, rank:'', grade:'', name: '#EmoCloche', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:18, rank:'', grade:'', name: '#Namescapes', score:0 , cols: 1, rows: 1}, 
  { id: 28, difficult:18, rank:'', grade:'', name: 'Elemental Creation -xiRemix-', score:0 , cols: 1, rows: 1}
]

export const DIFFICULTS_18P4: Difficult[] = [
  { id: 1, difficult:18, rank:'', grade:'', name: 'Verflucht', score:0 , cols: 1, rows: 1}, 
  { id: 2, difficult:18, rank:'', grade:'', name: '灼熱Beach Side Bunny', score:0 , cols: 1, rows: 1},
  { id: 3, difficult:18, rank:'', grade:'', name: '超☆超☆光☆速☆出☆前☆最☆速!!! スピード★スター★かなで', score:0 , cols: 1, rows: 1},
  { id: 4, difficult:18, rank:'', grade:'', name: 'こちら、幸福安心委員会です。', score:0 , cols: 1, rows: 1}, 
  { id: 5, difficult:18, rank:'', grade:'', name: 'Elemental Creation (kamome sano Remix)', score:0 , cols: 1, rows: 1},
  { id: 6, difficult:18, rank:'', grade:'', name: '永遠に幸せになる方法、見つけました。', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:18, rank:'', grade:'', name: 'End to end', score:0 , cols: 1, rows: 1}, 
  { id: 8, difficult:18, rank:'', grade:'', name: 'FLügeL《Λrp:ΣggyØ》', score:0 , cols: 1, rows: 1},
  { id: 9, difficult:18, rank:'', grade:'', name: 'CODE -CRiMSON-', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:18, rank:'', grade:'', name: 'HP:1', score:0 , cols: 1, rows: 1}, 
  { id: 11, difficult:18, rank:'', grade:'', name: 'Katharsis', score:0 , cols: 1, rows: 1},
  { id: 12, difficult:18, rank:'', grade:'', name: 'GEOMETRIA', score:0 , cols: 1, rows: 1},
  { id: 13, difficult:18, rank:'', grade:'', name: 'Garakuta Doll Play', score:0 , cols: 1, rows: 1}, 
  { id: 14, difficult:18, rank:'', grade:'', name: 'サイコパスラビット', score:0 , cols: 1, rows: 1}, 
  { id: 15, difficult:18, rank:'', grade:'', name: 'V', score:0 , cols: 1, rows: 1},
  { id: 16, difficult:18, rank:'', grade:'', name: 'Yum Yum Sweetie', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:18, rank:'', grade:'', name: 'そして黄金郷へ', score:0 , cols: 1, rows: 1}, 
  { id: 18, difficult:18, rank:'', grade:'', name: 'GERBERA', score:0 , cols: 1, rows: 1},
  { id: 19, difficult:18, rank:'', grade:'', name: 'ドーパミン', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:18, rank:'', grade:'', name: 'V.I.P.', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:18, rank:'', grade:'', name: 'PUPA', score:0 , cols: 1, rows: 1},
  { id: 22, difficult:18, rank:'', grade:'', name: 'Endless GRAVITY', score:0 , cols: 1, rows: 1},
  { id: 23, difficult:18, rank:'', grade:'', name: 'Hellfire', score:0 , cols: 1, rows: 1}, 
  { id: 24, difficult:18, rank:'', grade:'', name: 'croiX', score:0 , cols: 1, rows: 1}, 
  { id: 25, difficult:18, rank:'', grade:'', name: 'Rebellio', score:0 , cols: 1, rows: 1},
  { id: 26, difficult:18, rank:'', grade:'', name: '怒槌', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:18, rank:'', grade:'', name: 'Absurd Gaff', score:0 , cols: 1, rows: 1}, 
  { id: 28, difficult:18, rank:'', grade:'', name: 'HAVOX', score:0 , cols: 1, rows: 1},
  { id: 29, difficult:18, rank:'', grade:'', name: 'For UltraPlayers', score:0 , cols: 1, rows: 1}, 
  { id: 30, difficult:18, rank:'', grade:'', name: '緋色月下、狂咲ノ絶 (nayuta 2017 ver)', score:0 , cols: 1, rows: 1}
]

export const DIFFICULTS_18P3: Difficult[] = [
  { id: 1, difficult:18, rank:'', grade:'', name: '極圏', score:0 , cols: 1, rows: 1}, 
  { id: 2, difficult:18, rank:'', grade:'', name: 'Dreadnought', score:0 , cols: 1, rows: 1},
  { id: 3, difficult:18, rank:'', grade:'', name: 'FLOOR INFECTION Medley from SOUND VOLTEX×jubeat', score:0 , cols: 1, rows: 1},
  { id: 4, difficult:18, rank:'', grade:'', name: 'VALLIS-NERIA', score:0 , cols: 1, rows: 1}, 
  { id: 5, difficult:18, rank:'', grade:'', name: 'Fox4-Raize-', score:0 , cols: 1, rows: 1},
  { id: 6, difficult:18, rank:'', grade:'', name: 'LECTORIA', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:18, rank:'', grade:'', name: '極彩天奏', score:0 , cols: 1, rows: 1}, 
  { id: 8, difficult:18, rank:'', grade:'', name: 'KAC 2012 ULTIMATE MEDLEY -HISTORIA SOUND VOLTEX-', score:0 , cols: 1, rows: 1},
  { id: 9, difficult:18, rank:'', grade:'', name: 'Lachryma《Re:Queen’M》', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:18, rank:'', grade:'', name: 'She is my wife すーぱーアイドル☆ミツル子Remixちゃん', score:0 , cols: 1, rows: 1}, 
  { id: 11, difficult:18, rank:'', grade:'', name: 'POLICY BREAK Medley from SOUND VOLTEX×jubeat', score:0 , cols: 1, rows: 1},
  { id: 12, difficult:18, rank:'', grade:'', name: 'Prey', score:0 , cols: 1, rows: 1},
  { id: 13, difficult:18, rank:'', grade:'', name: 'DropZ-Line-', score:0 , cols: 1, rows: 1}, 
  { id: 14, difficult:18, rank:'', grade:'', name: 'Barbatos', score:0 , cols: 1, rows: 1}, 
  { id: 15, difficult:18, rank:'', grade:'', name: 'LegenD.', score:0 , cols: 1, rows: 1},
  { id: 16, difficult:18, rank:'', grade:'', name: '神獄烙桜', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:18, rank:'', grade:'', name: 'Re：Elemental Creation', score:0 , cols: 1, rows: 1}, 
  { id: 18, difficult:18, rank:'', grade:'', name: 'Nebulas', score:0 , cols: 1, rows: 1},
  { id: 19, difficult:18, rank:'', grade:'', name: 'Max Burning!!', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:18, rank:'', grade:'', name: 'FLOWER REDALiCE Remix', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:18, rank:'', grade:'', name: 'BLACK or WHITE?', score:0 , cols: 1, rows: 1},
  { id: 22, difficult:18, rank:'', grade:'', name: 'Lowermost revolt', score:0 , cols: 1, rows: 1},
  { id: 23, difficult:18, rank:'', grade:'', name: 'Dogeza Stairs', score:0 , cols: 1, rows: 1}, 
  { id: 24, difficult:18, rank:'', grade:'', name: 'Preserved Valkyria', score:0 , cols: 1, rows: 1}, 
  { id: 25, difficult:18, rank:'', grade:'', name: 'We Go Down', score:0 , cols: 1, rows: 1},
  { id: 26, difficult:18, rank:'', grade:'', name: '魔境堕天録サリエル', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:18, rank:'', grade:'', name: '星の透る夏空に願う', score:0 , cols: 1, rows: 1}, 
  { id: 28, difficult:18, rank:'', grade:'', name: 'The world of sound', score:0 , cols: 1, rows: 1},
  { id: 29, difficult:18, rank:'', grade:'', name: 'Wish upon Twin Stars', score:0 , cols: 1, rows: 1}, 
  { id: 30, difficult:18, rank:'', grade:'', name: 'Macuilxochitl (Latin Jazz Miz)', score:0 , cols: 1, rows: 1}
]

export const DIFFICULTS_18P2: Difficult[] = [
  { id: 1, difficult:18, rank:'', grade:'', name: '#Fairy_dancing_in_lake', score:0 , cols: 1, rows: 1}, 
  { id: 2, difficult:18, rank:'', grade:'', name: 'Gate of Atlantis', score:0 , cols: 1, rows: 1},
  { id: 3, difficult:18, rank:'', grade:'', name: 'アルティメットトゥルース -Phantasm-', score:0 , cols: 1, rows: 1},
  { id: 4, difficult:18, rank:'', grade:'', name: 'ULTRAVELOCITY', score:0 , cols: 1, rows: 1}, 
  { id: 5, difficult:18, rank:'', grade:'', name: 'Harpuia', score:0 , cols: 1, rows: 1},
  { id: 6, difficult:18, rank:'', grade:'', name: 'With It This Heaven?', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:18, rank:'', grade:'', name: 'GEMINI LA2ER', score:0 , cols: 1, rows: 1}, 
  { id: 8, difficult:18, rank:'', grade:'', name: 'Reb∞t', score:0 , cols: 1, rows: 1},
  { id: 9, difficult:18, rank:'', grade:'', name: '業焔繚乱', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:18, rank:'', grade:'', name: 'Khionos TiARA', score:0 , cols: 1, rows: 1}, 
  { id: 11, difficult:18, rank:'', grade:'', name: 'ouroboros -twin stroke of the end-', score:0 , cols: 1, rows: 1},
  { id: 12, difficult:18, rank:'', grade:'', name: '#Endroll', score:0 , cols: 1, rows: 1},
  { id: 13, difficult:18, rank:'', grade:'', name: 'ULTiMATE INFLATiON', score:0 , cols: 1, rows: 1}, 
  { id: 14, difficult:18, rank:'', grade:'', name: 'werewolf howls.', score:0 , cols: 1, rows: 1}, 
  { id: 15, difficult:18, rank:'', grade:'', name: 'Bangin\' Burst', score:0 , cols: 1, rows: 1},
  { id: 16, difficult:18, rank:'', grade:'', name: 'Quaint Echo', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:18, rank:'', grade:'', name: 'Puberty Dysthymia', score:0 , cols: 1, rows: 1}, 
  { id: 18, difficult:18, rank:'', grade:'', name: 'THE HEAVEN', score:0 , cols: 1, rows: 1},
  { id: 19, difficult:18, rank:'', grade:'', name: 'Noisy Minority', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:18, rank:'', grade:'', name: '消失', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:18, rank:'', grade:'', name: 'GALAXY BURST', score:0 , cols: 1, rows: 1},
  { id: 22, difficult:18, rank:'', grade:'', name: '伐折羅-vajra-', score:0 , cols: 1, rows: 1},
  { id: 23, difficult:18, rank:'', grade:'', name: 'Sky High', score:0 , cols: 1, rows: 1}, 
  { id: 24, difficult:18, rank:'', grade:'', name: 'Call of the World', score:0 , cols: 1, rows: 1}, 
  { id: 25, difficult:18, rank:'', grade:'', name: 'プログレなぞなぞクイズのテーマ', score:0 , cols: 1, rows: 1},
  { id: 26, difficult:18, rank:'', grade:'', name: 'POSSESSION (Aoi Q.E.D. RMX)', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:18, rank:'', grade:'', name: 'Air', score:0 , cols: 1, rows: 1}, 
  { id: 28, difficult:18, rank:'', grade:'', name: 'Destr0yer', score:0 , cols: 1, rows: 1},
  { id: 29, difficult:18, rank:'', grade:'', name: '1', score:0 , cols: 1, rows: 1}, 
  { id: 30, difficult:18, rank:'', grade:'', name: '1', score:0 , cols: 1, rows: 1}
]


export const DIFFICULTS_18P1: Difficult[] = [
  { id: 1, difficult:18, rank:'', grade:'', name: 'TRICKL4SH 220', score:0 , cols: 1, rows: 1}, 
  { id: 2, difficult:18, rank:'', grade:'', name: 'Nexta', score:0 , cols: 1, rows: 1},
  { id: 3, difficult:18, rank:'', grade:'', name: 'αρχη', score:0 , cols: 1, rows: 1},
  { id: 4, difficult:18, rank:'', grade:'', name: 'MODEL FT4', score:0 , cols: 1, rows: 1}, 
  { id: 5, difficult:18, rank:'', grade:'', name: 'PROVOES*PROPOSE <<êl fine>>', score:0 , cols: 1, rows: 1},
  { id: 6, difficult:18, rank:'', grade:'', name: 'Idola', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:18, rank:'', grade:'', name: 'HAELE III ~Angel Worlds~', score:0 , cols: 1, rows: 1}, 
  { id: 8, difficult:18, rank:'', grade:'', name: 'UnivEarth', score:0 , cols: 1, rows: 1},
  { id: 9, difficult:18, rank:'', grade:'', name: 'ムラサキグルマ', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:18, rank:'', grade:'', name: 'REVOLVER', score:0 , cols: 1, rows: 1}, 
  { id: 11, difficult:18, rank:'', grade:'', name: 'Broken 8cmix', score:0 , cols: 1, rows: 1},
  { id: 12, difficult:18, rank:'', grade:'', name: 'Turn the story', score:0 , cols: 1, rows: 1},
  { id: 13, difficult:18, rank:'', grade:'', name: '上海紅茶館 ～ Chinese Tea Orchid Remix', score:0 , cols: 1, rows: 1}, 
  { id: 14, difficult:18, rank:'', grade:'', name: 'のぼれ八坂坂！', score:0 , cols: 1, rows: 1}, 
  { id: 15, difficult:18, rank:'', grade:'', name: 'Gamerz FestivaL', score:0 , cols: 1, rows: 1},
  { id: 16, difficult:18, rank:'', grade:'', name: 'Solar Storm', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:18, rank:'', grade:'', name: 'Cloud 9', score:0 , cols: 1, rows: 1}, 
  { id: 18, difficult:18, rank:'', grade:'', name: '壊Rave*it!! 壊Rave*it!!', score:0 , cols: 1, rows: 1},
  { id: 19, difficult:18, rank:'', grade:'', name: 'Übertreffen', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:18, rank:'', grade:'', name: '光射す澪のユズリハ', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:18, rank:'', grade:'', name: 'INSECTICIDE', score:0 , cols: 1, rows: 1},
  { id: 22, difficult:18, rank:'', grade:'', name: 'MeteorGlow Aftermath', score:0 , cols: 1, rows: 1},
  { id: 23, difficult:18, rank:'', grade:'', name: '春告胡蝶', score:0 , cols: 1, rows: 1}, 
  { id: 24, difficult:18, rank:'', grade:'', name: 'Vanishing Eidos', score:0 , cols: 1, rows: 1}, 
  { id: 25, difficult:18, rank:'', grade:'', name: 'SuperMiracleEnsemble', score:0 , cols: 1, rows: 1},
  { id: 26, difficult:18, rank:'', grade:'', name: 'Metagame Matador', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:18, rank:'', grade:'', name: 'りむむむむむむ', score:0 , cols: 1, rows: 1}, 
  { id: 28, difficult:18, rank:'', grade:'', name: 'プナイプナイたいそう', score:0 , cols: 1, rows: 1},
  { id: 29, difficult:18, rank:'', grade:'', name: 'Your SOUL Is Mine', score:0 , cols: 1, rows: 1}, 
  { id: 30, difficult:18, rank:'', grade:'', name: '1', score:0 , cols: 1, rows: 1}
]


export const DIFFICULTS_18P0: Difficult[] = [
  { id: 1, difficult:18, rank:'', grade:'', name: 'VVelcome!!', score:0 , cols: 1, rows: 1}, 
  { id: 2, difficult:18, rank:'', grade:'', name: 'Over The Top', score:0 , cols: 1, rows: 1},
  { id: 3, difficult:18, rank:'', grade:'', name: 'トマヨイ', score:0 , cols: 1, rows: 1},
  { id: 4, difficult:18, rank:'', grade:'', name: 'm1dy Deluxe', score:0 , cols: 1, rows: 1}, 
  { id: 5, difficult:18, rank:'', grade:'', name: 'Celestial stinger', score:0 , cols: 1, rows: 1},
  { id: 6, difficult:18, rank:'', grade:'', name: 'Onigo', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:18, rank:'', grade:'', name: 'Scarlet Lance', score:0 , cols: 1, rows: 1}, 
  { id: 8, difficult:18, rank:'', grade:'', name: 'SociuS', score:0 , cols: 1, rows: 1},
  { id: 9, difficult:18, rank:'', grade:'', name: 'SACRIFICE feat.ayame', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:18, rank:'', grade:'', name: 'To:BrandNewDeadline', score:0 , cols: 1, rows: 1}, 
  { id: 11, difficult:18, rank:'', grade:'', name: 'Ops:Code-Rapture-', score:0 , cols: 1, rows: 1},
  { id: 12, difficult:18, rank:'', grade:'', name: 'Nostalgic Blood of the Strife', score:0 , cols: 1, rows: 1},
  { id: 13, difficult:18, rank:'', grade:'', name: 'NEO TREASON', score:0 , cols: 1, rows: 1}, 
  { id: 14, difficult:18, rank:'', grade:'', name: 'Glitter Flatter Scatter', score:0 , cols: 1, rows: 1}, 
  { id: 15, difficult:18, rank:'', grade:'', name: 'Pulsar', score:0 , cols: 1, rows: 1},
  { id: 16, difficult:18, rank:'', grade:'', name: 'Angels And Demons', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:18, rank:'', grade:'', name: 'XyHATTE', score:0 , cols: 1, rows: 1}, 
  { id: 18, difficult:18, rank:'', grade:'', name: 'Wings of Glory', score:0 , cols: 1, rows: 1},
  { id: 19, difficult:18, rank:'', grade:'', name: 'オニユリ', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:18, rank:'', grade:'', name: 'BlueMoon Princess', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:18, rank:'', grade:'', name: 'Ghost Trigger', score:0 , cols: 1, rows: 1},
  { id: 22, difficult:18, rank:'', grade:'', name: 'Midnight City Warfare', score:0 , cols: 1, rows: 1},
  { id: 23, difficult:18, rank:'', grade:'', name: 'Cepheus', score:0 , cols: 1, rows: 1}, 
  { id: 24, difficult:18, rank:'', grade:'', name: 'Juggler\'s Maddness', score:0 , cols: 1, rows: 1}, 
  { id: 25, difficult:18, rank:'', grade:'', name: 'Xepher Light and Darkness Dragon REMIX', score:0 , cols: 1, rows: 1},
  { id: 26, difficult:18, rank:'', grade:'', name: 'WARNING×WARNING×WARNING', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:18, rank:'', grade:'', name: 'EGOISM 440 (Ange;art remix)', score:0 , cols: 1, rows: 1}, 
  { id: 28, difficult:18, rank:'', grade:'', name: 'ばらんが!!!!', score:0 , cols: 1, rows: 1},
  { id: 29, difficult:18, rank:'', grade:'', name: '1', score:0 , cols: 1, rows: 1}, 
  { id: 30, difficult:18, rank:'', grade:'', name: '1', score:0 , cols: 1, rows: 1}
]


export const DIFFICULTS_18M1: Difficult[] = [
  { id: 1, difficult:18, rank:'', grade:'', name: 'Ichi-Go! DX Pancake!', score:0 , cols: 1, rows: 1}, 
  { id: 2, difficult:18, rank:'', grade:'', name: 'Ring！Run！Nyan!!', score:0 , cols: 1, rows: 1},
  { id: 3, difficult:18, rank:'', grade:'', name: 'JǛPITΨR ♃ GЯÃVITÝ', score:0 , cols: 1, rows: 1},
  { id: 4, difficult:18, rank:'', grade:'', name: 'Glorious Journey', score:0 , cols: 1, rows: 1}, 
  { id: 5, difficult:18, rank:'', grade:'', name: 'MeteorA', score:0 , cols: 1, rows: 1},
  { id: 6, difficult:18, rank:'', grade:'', name: 'FIRST：DREAMS', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:18, rank:'', grade:'', name: 'タイムトラベル', score:0 , cols: 1, rows: 1}, 
  { id: 8, difficult:18, rank:'', grade:'', name: 'Aurolla', score:0 , cols: 1, rows: 1},
  { id: 9, difficult:18, rank:'', grade:'', name: 'ΩVERFLOW', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:18, rank:'', grade:'', name: 'ECHIDNA', score:0 , cols: 1, rows: 1}, 
  { id: 11, difficult:18, rank:'', grade:'', name: 'Destiny', score:0 , cols: 1, rows: 1},
  { id: 12, difficult:18, rank:'', grade:'', name: 'L9', score:0 , cols: 1, rows: 1},
  { id: 13, difficult:18, rank:'', grade:'', name: '蛇神', score:0 , cols: 1, rows: 1}, 
  { id: 14, difficult:18, rank:'', grade:'', name: 'ΑΩ', score:0 , cols: 1, rows: 1}, 
  { id: 15, difficult:18, rank:'', grade:'', name: 'メイビ～初恋！？ビスケット☆大作戦', score:0 , cols: 1, rows: 1},
  { id: 16, difficult:18, rank:'', grade:'', name: 'CHERNOBOG', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:18, rank:'', grade:'', name: 'まじかる生主＠りすなちゃん', score:0 , cols: 1, rows: 1}, 
  { id: 18, difficult:18, rank:'', grade:'', name: 'Gorgetech', score:0 , cols: 1, rows: 1},
  { id: 19, difficult:18, rank:'', grade:'', name: 'Firestorm', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:18, rank:'', grade:'', name: 'ΣmbryØ', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:18, rank:'', grade:'', name: 'GaLaXyEggPlanT', score:0 , cols: 1, rows: 1},
  { id: 22, difficult:18, rank:'', grade:'', name: 'Pon-Pon-Pompoko Dai-Sen-Saw!', score:0 , cols: 1, rows: 1},
  { id: 23, difficult:18, rank:'', grade:'', name: '†渚の小悪魔ラヴリィ～レイディオ†', score:0 , cols: 1, rows: 1}, 
  { id: 24, difficult:18, rank:'', grade:'', name: '消失(Hommarju Remix)', score:0 , cols: 1, rows: 1}, 
  { id: 25, difficult:18, rank:'', grade:'', name: 'LastΩmegA', score:0 , cols: 1, rows: 1},
  { id: 26, difficult:18, rank:'', grade:'', name: 'Make Magic', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:18, rank:'', grade:'', name: '冥天・ヘメロカリス', score:0 , cols: 1, rows: 1}, 
  { id: 28, difficult:18, rank:'', grade:'', name: 'memento mori -intro-', score:0 , cols: 1, rows: 1},
  { id: 29, difficult:18, rank:'', grade:'', name: '世界の果てに約束の凱歌を -VOLTEX Mix-', score:0 , cols: 1, rows: 1}, 
  { id: 30, difficult:18, rank:'', grade:'', name: 'PSYCHO+HEROES', score:0 , cols: 1, rows: 1}
]


export const DIFFICULTS_18M2: Difficult[] = [
  { id: 1, difficult:18, rank:'', grade:'', name: 'Innocent', score:0 , cols: 1, rows: 1}, 
  { id: 2, difficult:18, rank:'', grade:'', name: 'Electric Injury', score:0 , cols: 1, rows: 1},
  { id: 3, difficult:18, rank:'', grade:'', name: '666', score:0 , cols: 1, rows: 1},
  { id: 4, difficult:18, rank:'', grade:'', name: 'Cloud Crasher', score:0 , cols: 1, rows: 1}, 
  { id: 5, difficult:18, rank:'', grade:'', name: 'mqlo', score:0 , cols: 1, rows: 1},
  { id: 6, difficult:18, rank:'', grade:'', name: 'Lunatic Sprinter', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:18, rank:'', grade:'', name: 'Nhelv', score:0 , cols: 1, rows: 1}, 
  { id: 8, difficult:18, rank:'', grade:'', name: 'Angelic Jelly', score:0 , cols: 1, rows: 1},
  { id: 9, difficult:18, rank:'', grade:'', name: 'XROSS THE XOUL', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:18, rank:'', grade:'', name: 'Invitation from Mr.C', score:0 , cols: 1, rows: 1}, 
  { id: 11, difficult:18, rank:'', grade:'', name: 'Sudden Visitor', score:0 , cols: 1, rows: 1},
  { id: 12, difficult:18, rank:'', grade:'', name: 'Warriors Aboot', score:0 , cols: 1, rows: 1},
  { id: 13, difficult:18, rank:'', grade:'', name: 'Levier\'n NābYss', score:0 , cols: 1, rows: 1}, 
  { id: 14, difficult:18, rank:'', grade:'', name: 'BEAST BASS BOMB', score:0 , cols: 1, rows: 1}, 
  { id: 15, difficult:18, rank:'', grade:'', name: 'lEyl', score:0 , cols: 1, rows: 1},
  { id: 16, difficult:18, rank:'', grade:'', name: 'Be a Hero!', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:18, rank:'', grade:'', name: 'ΣgØ', score:0 , cols: 1, rows: 1}, 
  { id: 18, difficult:18, rank:'', grade:'', name: 'Spirit of the Beast', score:0 , cols: 1, rows: 1},
  { id: 19, difficult:18, rank:'', grade:'', name: 'RHYZING BEAT', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:18, rank:'', grade:'', name: 'IKAROS DYNAMITE!!!!', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:18, rank:'', grade:'', name: '無魎大数', score:0 , cols: 1, rows: 1},
  { id: 22, difficult:18, rank:'', grade:'', name: '孤独の番人', score:0 , cols: 1, rows: 1},
  { id: 23, difficult:18, rank:'', grade:'', name: 'veRtrageS', score:0 , cols: 1, rows: 1}, 
  { id: 24, difficult:18, rank:'', grade:'', name: 'Sacrifice and Faith', score:0 , cols: 1, rows: 1}, 
  { id: 25, difficult:18, rank:'', grade:'', name: 'Evans', score:0 , cols: 1, rows: 1},
  { id: 26, difficult:18, rank:'', grade:'', name: '怪盗Ｆの台本～消えたダイヤの謎～', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:18, rank:'', grade:'', name: 'Atropa bella-donna', score:0 , cols: 1, rows: 1}, 
  { id: 28, difficult:18, rank:'', grade:'', name: 'Valanga(polysha Remix)', score:0 , cols: 1, rows: 1},
  { id: 29, difficult:18, rank:'', grade:'', name: 'EMERALDAS (Yuta Imai Remix)', score:0 , cols: 1, rows: 1}, 
  { id: 30, difficult:18, rank:'', grade:'', name: 'Souhait bleu', score:0 , cols: 1, rows: 1}
]

export const DIFFICULTS_18M3: Difficult[] = [
  { id: 1, difficult:18, rank:'', grade:'', name: 'セイクリッド ルイン', score:0 , cols: 1, rows: 1}, 
  { id: 2, difficult:18, rank:'', grade:'', name: 'Butterfly Twist', score:0 , cols: 1, rows: 1},
  { id: 3, difficult:18, rank:'', grade:'', name: 'Divine\'s or Deal', score:0 , cols: 1, rows: 1},
  { id: 4, difficult:18, rank:'', grade:'', name: 'Growth Memories', score:0 , cols: 1, rows: 1}, 
  { id: 5, difficult:18, rank:'', grade:'', name: 'Beyond the BLUE', score:0 , cols: 1, rows: 1},
  { id: 6, difficult:18, rank:'', grade:'', name: 'Goddess Bless you', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:18, rank:'', grade:'', name: 'Black Lotus', score:0 , cols: 1, rows: 1}, 
  { id: 8, difficult:18, rank:'', grade:'', name: 'Crack Traxxxx', score:0 , cols: 1, rows: 1},
  { id: 9, difficult:18, rank:'', grade:'', name: 'Teufel', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:18, rank:'', grade:'', name: 'WHITEOUT', score:0 , cols: 1, rows: 1}, 
  { id: 11, difficult:18, rank:'', grade:'', name: 'ランカーキラーガール', score:0 , cols: 1, rows: 1},
  { id: 12, difficult:18, rank:'', grade:'', name: '絶対零度', score:0 , cols: 1, rows: 1},
  { id: 13, difficult:18, rank:'', grade:'', name: 'Demise Quartet', score:0 , cols: 1, rows: 1}, 
  { id: 14, difficult:18, rank:'', grade:'', name: 'VILE CAT', score:0 , cols: 1, rows: 1}, 
  { id: 15, difficult:18, rank:'', grade:'', name: 'The Golden Era', score:0 , cols: 1, rows: 1},
  { id: 16, difficult:18, rank:'', grade:'', name: 'ホワイトパレード', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:18, rank:'', grade:'', name: 'マサカリブレイド', score:0 , cols: 1, rows: 1}, 
  { id: 18, difficult:18, rank:'', grade:'', name: 'Qubism', score:0 , cols: 1, rows: 1},
  { id: 19, difficult:18, rank:'', grade:'', name: 'NEO GRAVITY', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:18, rank:'', grade:'', name: 'Jack-the-Ripper◆', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:18, rank:'', grade:'', name: 'Catch Our Fire!', score:0 , cols: 1, rows: 1},
  { id: 22, difficult:18, rank:'', grade:'', name: '雷鼓サンダービート', score:0 , cols: 1, rows: 1},
  { id: 23, difficult:18, rank:'', grade:'', name: '侍Annihilate!!', score:0 , cols: 1, rows: 1}, 
  { id: 24, difficult:18, rank:'', grade:'', name: '到達してしまった僕らと夢と希望の最之果', score:0 , cols: 1, rows: 1}, 
  { id: 25, difficult:18, rank:'', grade:'', name: 'Vividly Impromptu', score:0 , cols: 1, rows: 1},
  { id: 26, difficult:18, rank:'', grade:'', name: 'Taiko Drum Monster', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:18, rank:'', grade:'', name: 'Touch My Body', score:0 , cols: 1, rows: 1}, 
  { id: 28, difficult:18, rank:'', grade:'', name: 'Seraphim', score:0 , cols: 1, rows: 1},
  { id: 29, difficult:18, rank:'', grade:'', name: 'ラヴ♡チャンス!!', score:0 , cols: 1, rows: 1}, 
  { id: 30, difficult:18, rank:'', grade:'', name: 'FEEL THE FORCE', score:0 , cols: 1, rows: 1}
]


export const DIFFICULTS_18M4: Difficult[] = [
  { id: 1, difficult:18, rank:'', grade:'', name: 'Leviathan', score:0 , cols: 1, rows: 1}, 
  { id: 2, difficult:18, rank:'', grade:'', name: 'ファイナルレター', score:0 , cols: 1, rows: 1},
  { id: 3, difficult:18, rank:'', grade:'', name: 'Evans VolteX Pf arrange', score:0 , cols: 1, rows: 1},
  { id: 4, difficult:18, rank:'', grade:'', name: 'Our Love', score:0 , cols: 1, rows: 1}, 
  { id: 5, difficult:18, rank:'', grade:'', name: 'V Sen5eS', score:0 , cols: 1, rows: 1},
  { id: 6, difficult:18, rank:'', grade:'', name: 'C18H27NO3', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:18, rank:'', grade:'', name: 'Lazurite', score:0 , cols: 1, rows: 1}, 
  { id: 8, difficult:18, rank:'', grade:'', name: 'Night Rockin\' Bird', score:0 , cols: 1, rows: 1},
  { id: 9, difficult:18, rank:'', grade:'', name: 'JEHANNEDARC', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:18, rank:'', grade:'', name: 'Renegade Fruits', score:0 , cols: 1, rows: 1}, 
  { id: 11, difficult:18, rank:'', grade:'', name: 'Theme of Ricerca', score:0 , cols: 1, rows: 1},
  { id: 12, difficult:18, rank:'', grade:'', name: 'Sweet Requiem', score:0 , cols: 1, rows: 1},
  { id: 13, difficult:18, rank:'', grade:'', name: 'PARTY TIME!', score:0 , cols: 1, rows: 1}, 
  { id: 14, difficult:18, rank:'', grade:'', name: 'Jacob’s Elevator', score:0 , cols: 1, rows: 1}, 
  { id: 15, difficult:18, rank:'', grade:'', name: 'Prayer', score:0 , cols: 1, rows: 1},
  { id: 16, difficult:18, rank:'', grade:'', name: 'tricky trick', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:18, rank:'', grade:'', name: 'お米の美味しい炊き方、そしてお米を食べることによるその効果。', score:0 , cols: 1, rows: 1}, 
  { id: 18, difficult:18, rank:'', grade:'', name: 'eighth-slave', score:0 , cols: 1, rows: 1},
  { id: 19, difficult:18, rank:'', grade:'', name: '誰が為に兎は舞う＝狂速狂騒曲＝', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:18, rank:'', grade:'', name: 'FLOWER', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:18, rank:'', grade:'', name: 'Redshift', score:0 , cols: 1, rows: 1},
  { id: 22, difficult:18, rank:'', grade:'', name: '月光乱舞', score:0 , cols: 1, rows: 1},
  { id: 23, difficult:18, rank:'', grade:'', name: 'Cynical Joker', score:0 , cols: 1, rows: 1}, 
  { id: 24, difficult:18, rank:'', grade:'', name: 'SUPER SUMMER SALE', score:0 , cols: 1, rows: 1}, 
  { id: 25, difficult:18, rank:'', grade:'', name: 'ワールズエンド・ダンスホール', score:0 , cols: 1, rows: 1},
  { id: 26, difficult:18, rank:'', grade:'', name: 'FIRE IN MY HEART', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:18, rank:'', grade:'', name: 'Thank you for your playing music', score:0 , cols: 1, rows: 1}, 
  { id: 28, difficult:18, rank:'', grade:'', name: 'Symphonic Tear', score:0 , cols: 1, rows: 1},
  { id: 29, difficult:18, rank:'', grade:'', name: 'Defining Future', score:0 , cols: 1, rows: 1}, 
  { id: 30, difficult:18, rank:'', grade:'', name: '€omet popcorn', score:0 , cols: 1, rows: 1}
]


export const DIFFICULTS_18M5: Difficult[] = [
  { id: 1, difficult:18, rank:'', grade:'', name: 'apo:llioth', score:0 , cols: 1, rows: 1}, 
  { id: 2, difficult:18, rank:'', grade:'', name: 'Valkyrja ~Aldrlag~', score:0 , cols: 1, rows: 1},
  { id: 3, difficult:18, rank:'', grade:'', name: 'Blessing Bouquet', score:0 , cols: 1, rows: 1},
  { id: 4, difficult:18, rank:'', grade:'', name: 'New Decade', score:0 , cols: 1, rows: 1}, 
  { id: 5, difficult:18, rank:'', grade:'', name: 'おお われら喜び讃うべし、主よ', score:0 , cols: 1, rows: 1},
  { id: 6, difficult:18, rank:'', grade:'', name: 'Triple Counter', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:18, rank:'', grade:'', name: '狂水一華', score:0 , cols: 1, rows: 1}, 
  { id: 8, difficult:18, rank:'', grade:'', name: 'Fin.ArcDeaR', score:0 , cols: 1, rows: 1},
  { id: 9, difficult:18, rank:'', grade:'', name: 'アオアラシ', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:18, rank:'', grade:'', name: 'The Formula', score:0 , cols: 1, rows: 1}, 
  { id: 11, difficult:18, rank:'', grade:'', name: 'petits fours', score:0 , cols: 1, rows: 1},
  { id: 12, difficult:18, rank:'', grade:'', name: 'Typhoon Craaash!!', score:0 , cols: 1, rows: 1},
  { id: 13, difficult:18, rank:'', grade:'', name: 'Enchanté', score:0 , cols: 1, rows: 1}, 
  { id: 14, difficult:18, rank:'', grade:'', name: 'ドリームエンド・サバイバー', score:0 , cols: 1, rows: 1}, 
  { id: 15, difficult:18, rank:'', grade:'', name: 'Xicholauncher', score:0 , cols: 1, rows: 1},
  { id: 16, difficult:18, rank:'', grade:'', name: '翠雨の祷', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:18, rank:'', grade:'', name: '最小三倍完全数', score:0 , cols: 1, rows: 1}, 
  { id: 18, difficult:18, rank:'', grade:'', name: 'ねこみみ(=ФωФ=)ぱんでみみっく', score:0 , cols: 1, rows: 1},
  { id: 19, difficult:18, rank:'', grade:'', name: 'Boss Rush', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:18, rank:'', grade:'', name: 'GAIA', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:18, rank:'', grade:'', name: 'Яe\'s NoVǢ', score:0 , cols: 1, rows: 1},
  { id: 22, difficult:18, rank:'', grade:'', name: '恋歌疾風！かるたクイーンいろは', score:0 , cols: 1, rows: 1},
  { id: 23, difficult:18, rank:'', grade:'', name: 'Victim of Nights', score:0 , cols: 1, rows: 1}, 
  { id: 24, difficult:18, rank:'', grade:'', name: 'Hurt me plenty', score:0 , cols: 1, rows: 1}, 
  { id: 25, difficult:18, rank:'', grade:'', name: 'Ok!! Hug Me', score:0 , cols: 1, rows: 1},
  { id: 26, difficult:18, rank:'', grade:'', name: '↓↓↓', score:0 , cols: 1, rows: 1},
  { id: 27, difficult:18, rank:'', grade:'', name: 'Sakura Reflection (P*Light Slayer Remix)', score:0 , cols: 1, rows: 1}, 
  { id: 28, difficult:18, rank:'', grade:'', name: 'OPEN MY GATE', score:0 , cols: 1, rows: 1},
  { id: 29, difficult:18, rank:'', grade:'', name: 'nostos -ark remix-', score:0 , cols: 1, rows: 1}, 
  { id: 30, difficult:18, rank:'', grade:'', name: 'eternite', score:0 , cols: 1, rows: 1}
]


export const DIFFICULTS_18M6: Difficult[] = [
  { id: 1, difficult:18, rank:'', grade:'', name: 'Ethereal Lotus', score:0 , cols: 1, rows: 1}, 
  { id: 2, difficult:18, rank:'', grade:'', name: 'SLEEPWALKER', score:0 , cols: 1, rows: 1},
  { id: 3, difficult:18, rank:'', grade:'', name: 'MAYHEM', score:0 , cols: 1, rows: 1},
  { id: 4, difficult:18, rank:'', grade:'', name: 'rE:Voltagers', score:0 , cols: 1, rows: 1}, 
  { id: 5, difficult:18, rank:'', grade:'', name: 'Liar rain', score:0 , cols: 1, rows: 1},
  { id: 6, difficult:18, rank:'', grade:'', name: 'World of Iris', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:18, rank:'', grade:'', name: 'Barbless Ego', score:0 , cols: 1, rows: 1}, 
  { id: 8, difficult:18, rank:'', grade:'', name: 'Φnd:you', score:0 , cols: 1, rows: 1},
  { id: 9, difficult:18, rank:'', grade:'', name: 'Akzeriyyuth', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:18, rank:'', grade:'', name: 'BLAZING_LAZER', score:0 , cols: 1, rows: 1}, 
  { id: 11, difficult:18, rank:'', grade:'', name: 'Mynarco(Nagomu 2Step Remix)', score:0 , cols: 1, rows: 1},
  { id: 12, difficult:18, rank:'', grade:'', name: '幻想のサテライト', score:0 , cols: 1, rows: 1},
  { id: 13, difficult:18, rank:'', grade:'', name: '月々紅花', score:0 , cols: 1, rows: 1}, 
  { id: 14, difficult:18, rank:'', grade:'', name: '腐れ外道とチョコレゐト', score:0 , cols: 1, rows: 1}, 
  { id: 15, difficult:18, rank:'', grade:'', name: 'New Leaf', score:0 , cols: 1, rows: 1},
  { id: 16, difficult:18, rank:'', grade:'', name: 'MONOLITH', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:18, rank:'', grade:'', name: 'Bolérrot', score:0 , cols: 1, rows: 1}, 
  { id: 18, difficult:18, rank:'', grade:'', name: 'ミッドナイト☆WAR', score:0 , cols: 1, rows: 1},
  { id: 19, difficult:18, rank:'', grade:'', name: 'Innocent Azure', score:0 , cols: 1, rows: 1},
  { id: 20, difficult:18, rank:'', grade:'', name: '恋愛♡悪戯！？まじかる☆ぱふゅ～む！！', score:0 , cols: 1, rows: 1},
  { id: 21, difficult:18, rank:'', grade:'', name: '冥 Rockin\' SWING REMIX', score:0 , cols: 1, rows: 1},
  { id: 22, difficult:18, rank:'', grade:'', name: '金縛りの逢を', score:0 , cols: 1, rows: 1},
  { id: 23, difficult:18, rank:'', grade:'', name: 'おはようからおやすみまでかまってポメポメ', score:0 , cols: 1, rows: 1}, 
  { id: 24, difficult:18, rank:'', grade:'', name: '金縛りの逢を', score:0 , cols: 1, rows: 1}, 
  { id: 25, difficult:18, rank:'', grade:'', name: 'ホイホイ☆幻想ホロイズム', score:0 , cols: 1, rows: 1}
]


export const DIFFICULTS_18M7: Difficult[] = [
  { id: 1, difficult:18, rank:'', grade:'', name: '最終鬼畜妹フランドール・S', score:0 , cols: 1, rows: 1}, 
  { id: 2, difficult:18, rank:'', grade:'', name: '真っ白な靴', score:0 , cols: 1, rows: 1},
  { id: 3, difficult:18, rank:'', grade:'', name: 'Opium and Purple haze', score:0 , cols: 1, rows: 1},
  { id: 4, difficult:18, rank:'', grade:'', name: 'KIMIDORI Streak!!', score:0 , cols: 1, rows: 1}, 
  { id: 5, difficult:18, rank:'', grade:'', name: 'OZONE', score:0 , cols: 1, rows: 1},
  { id: 6, difficult:18, rank:'', grade:'', name: 'Unicorn tail Dustboxxxx RMX', score:0 , cols: 1, rows: 1},
  { id: 7, difficult:18, rank:'', grade:'', name: 'スラッシュ//シスターズ', score:0 , cols: 1, rows: 1}, 
  { id: 8, difficult:18, rank:'', grade:'', name: 'METATRON', score:0 , cols: 1, rows: 1},
  { id: 9, difficult:18, rank:'', grade:'', name: 'Believe In Yourself', score:0 , cols: 1, rows: 1},
  { id: 10, difficult:18, rank:'', grade:'', name: 'びいすと！', score:0 , cols: 1, rows: 1}, 
  { id: 11, difficult:18, rank:'', grade:'', name: 'She Turns Me On', score:0 , cols: 1, rows: 1},
  { id: 12, difficult:18, rank:'', grade:'', name: 'REDO the NIGHT', score:0 , cols: 1, rows: 1},
  { id: 13, difficult:18, rank:'', grade:'', name: 'ミュージックプレイヤー', score:0 , cols: 1, rows: 1}, 
  { id: 14, difficult:18, rank:'', grade:'', name: 'Black night', score:0 , cols: 1, rows: 1}, 
  { id: 15, difficult:18, rank:'', grade:'', name: '水簾ノ調', score:0 , cols: 1, rows: 1},
  { id: 16, difficult:18, rank:'', grade:'', name: 'ALTONA', score:0 , cols: 1, rows: 1},
  { id: 17, difficult:18, rank:'', grade:'', name: '諏訪大信仰', score:0 , cols: 1, rows: 1}, 
  { id: 18, difficult:18, rank:'', grade:'', name: '1', score:0 , cols: 1, rows: 1}
]

export const SKILL = [
  'Level.∞ 暴龍天', 'Level.11 或帝滅斗', 'Level.10 剛力羅'
]